- PDO.php
PHP 5.6 triggers `PDO::PGSQL_ATTR_DISABLE_NATIVE_PREPARED_STATEMENT is deprecated, use PDO::ATTR_EMULATE_PREPARES instead`
> Deprecated PDO::PGSQL_ATTR_DISABLE_NATIVE_PREPARED_STATEMENT

- Core.php
Added third argument to "is_subclass_of" (supported from PHP 5.3.9), which caused the following Code Smell message: ""Method call uses 3 parameters, but method signature uses 2 parameters".
> Added third argument to "is_subclass_of"

- gmp.php
See also
http://php.net/manual/en/function.gmp-export.php
http://php.net/manual/en/function.gmp-import.php
http://php.net/manual/en/function.gmp-root.php
http://php.net/manual/en/function.gmp-rootrem.php
Fixes https://youtrack.jetbrains.com/issue/WI-28534
> Added missing gmp functions and constants introduced with PHP 5.6.0 and 5.6.1

- standard_2.php
`levenshtein` function in PHP supports either 2 or 5 arguments, and this PR allows to don't warn on calls with 5 arguments. I'm not sure the case of 2 and 5 arguments can be covered by phpDocs syntax, and thus there is an issue in this PR: calls to `levenshtein` with 3 or 4 arguments will not be marked as incorrect. Maybe an `Annotator` class can be written to handle this case, but I'm not sure it's worth it. So, let you make a choice about merging.
> Support `levenshtein` function with 5 parameters

- standard_2.php
The [documentation](http://php.net/manual/en/function.parse-url.php) has changed since the stub has been written. In particular, then changelog states:
> 5.3.3	Removed the E_WARNING that was emitted when URL parsing failed.
> Update the parse_url() stub

- Reflection.php
- Duplicate of `isGenerator` method
> Remove duplicate isGenerator definition

- Reflection.php
- Missing docblock for `ReflectionFunctionAbstract::getClosureScopeClass`
> Added missing docblock for autocompletion

- gmagick.php
This adds stubs for all Gmagick classes, resolving [WI-17163](https://youtrack.jetbrains.com/issue/WI-17163).
I took great care to match the online documentation, *and* the [extension's source code](https://github.com/vitoc/gmagick), submitting [many bug reports](https://bugs.php.net/search.php?cmd=display&search_for=Gmagick&author_email=benjamin.morel%40gmail.com&order_by=ts1&direction=ASC&limit=30&status=All&reorder_by=ts1) to the PHP documentation, that are now fixed or being fixed.
These stubs are up to date with the corrected documentation.
> Gmagick stubs

- xdebug.php
I updated the doc based on https://xdebug.org/docs/all_functions to include all missing arguments (and I opened a bug on Xdebug to report the fact that they are not exposed through the reflection API: https://bugs.xdebug.org/view.php?id=1300)
> Update the XDebug stubs

- standard_0.php
Fix the php >= 5.2.3 double_encode argument for `htmlentities` default as null when it is defined as true like `htmlspecialchars`
Reference: http://php.net/manual/en/function.htmlentities.php
> htmlentities double_encode not null

- memcache.php
When using Memcache methods, those get annotated by the "Method call or class usage is not case sensitive" Inspection.
:octocat:
> Fix case in Memcache method names

- date_c.php
Added missing DatePeriod methods:
* [getDateInterval](http://php.net/manual/en/dateperiod.getdateinterval.php)
* [getEndDate](http://php.net/manual/en/dateperiod.getenddate.php)
* [getStartDate](http://php.net/manual/en/dateperiod.getstartdate.php)
> Added DatePeriod missing methods

- dom_c.php
WI-31566 Wrong number of function parameters DOMDocument::schemaValidate (code inspection) https://youtrack.jetbrains.com/issue/WI-31566
> Wrong number of function parameters DOMDocument::schemaValidate fix

- mongodb.php
This was a bit lacking and didn't properly reflect how you can use the class.
> Correct and complete mongo-php-driver ObjectID documentation

- mongodb.php
> Fixing wrong stubs on MongoDB classes

- dom_c.php
As of http://php.net/manual/en/class.domnamednodemap.php,  `DOMNamedNodeMap implements Traversable `
Verify by running
`
<?php assert(new DOMNamedNodeMap() instanceof Traversable);
`
Unfortunately, Intellij warns about DOMNamedNodeMap not implementing Traversable
> DOMNamedNodeMap implements Traversable

- mongodb.php
`MongoDB\Driver\WriteConcern::__construct` expects only 3 parameters, not 4 ([check docs](http://php.net/manual/en/mongodb-driver-writeconcern.construct.php)).
Furthermore the first parameter can be an integer, not only a string.
> MongoDB\Driver\WriteConcern::__construct expects only 3 parameters

- standard/mongodb.php
The method `\MongoDB\Driver\Manager::getReadConcern()` is missing.
Unfortunately it is not documented on [php.net](http://php.net/manual/en/class.mongodb-driver-manager.php) at the moment, but we can see it in [the source code](https://github.com/mongodb/mongo-php-driver/blob/5076fb026f642ec3ced6da85c6759a8175459b32/src/MongoDB/Manager.c#L198).
> add \MongoDB\Driver\Manager::getReadConcern()

- standard/PDO.php
Added 4th `PDO::query` method parameter `$ctorargs`, which is used to send data to the constructor of an object when using `PDO::FETCH_CLASS` Similar to `PDOStatement::fetchObject` usage.
Reference, third usage example: http://php.net/manual/en/pdo.query.php 
Fixed  `PDOStatement` default parameter values in `fetchAll` and `fetchObject` methods.
> PDO::query 4th parameter

- standard/mongodb.php
Methods [executeCommand](http://php.net/manual/en/mongodb-driver-server.executecommand.php) and [executeQuery](http://php.net/manual/en/mongodb-driver-server.executequery.php) from MongoDB\Driver\Server have a third parameter.
> Methods executeCommand and executeQuery have a third parameter

- standard/PDO.php
Docs page: http://php.net/manual/en/ref.pdo-mysql.php#pdo-mysql.constants
Definition in the php source file: https://github.com/php/php-src/blob/master/ext/pdo_mysql/php_pdo_mysql_int.h#L181
> Add PDO::MYSQL_ATTR_MULTI_STATEMENTS constant

- standard/xmlwriter.php
According to PHP documentation, the prefix should be "NS" instead of "Ns".
http://php.net/manual/en/function.xmlwriter-write-attribute-ns.php
http://php.net/manual/en/function.xmlwriter-start-attribute-ns.php
http://php.net/manual/en/function.xmlwriter-write-element-ns.php
http://php.net/manual/en/function.xmlwriter-start-element-ns.php
> Ns => NS, according to PHP documentation.

- standard/intl.php
The documentation for [Collator::__construct()](http://php.net/manual/en/collator.construct.php) leaves no ambiguity, this should be `string $locale`.
> Update Collator constructor argument

- standard/yaml.php
https://youtrack.jetbrains.com/issue/WI-33988
Reference: http://php.net/yaml-emit
> Resolves WI-33988: yaml_emit stub missing

- standard/intl.php
**This PR covers WI-34325**
The intl stubs are missing the UConverter class of the intl extension. PHPStorm marks all usages of UConverter as a unknown class.
This PR provides the missing stubs to make the class known to PHPStorm.
> WI-34325 Missing UConverter stubs for intl

- standard/gmp.php
I made this change to remove an inspection warning in PhpStorm.
> Changed the return type in php doc for gmp_sub from "resource" to "GMP"

- standard/date_c.php
When the interval_spec cannot be parsed as an interval an \Exception is thrown from the constructor
> Update date_c DateInterval Constructor docBlock

- standard/date_c.php
- Most methods fixed according to php behaviour (see https://3v4l.org/GlZGq) (`$this` to `static` is just for consistency)
- Magic method __wakeup fixed according to php documentation
- DatePeriod getters is just an attempt to describe weird implementation (see https://3v4l.org/TqasA)
> Fix return phpdocs in date_c

- standard/curl_d.php
This closes https://youtrack.jetbrains.com/issue/WI-29746
> Added CURLOPT_POSTREDIR, which has been available since 5.3.2

- standard/standard_0.php
- standard/standard_1.php
- standard/standard_2.php
- standard/standard_3.php
- standard/standard_4.php
- standard/standard_5.php
- standard/standard_6.php
- standard/standard_7.php
- standard/standard_8.php
- standard/standard_9.php
It was pointed out @ https://github.com/etsy/phan/issues/55#issuecomment-276126690 that many of these are wrong.
This adds the bool return type for methods that are marked as returning false on failure.
> Fix bool on failure returns in standards

- standard/standard_5.php
* Bring the description and parameter docs for `file_get_contents` and `file_put_contents` into line with the current PHP documentation.
* Removed references to PHP version 6.
* See https://youtrack.jetbrains.com/issue/WI-31762
> Stub fixes for file_get_contents and file_put_contents

- standard/date_c.php
PHP 7.1 introduced microsecond support for DateTime(Immutable)::setTime, see https://3v4l.org/2R4fU
Correct @return value for setTime, which can be false when setTime fails.
> Update stub for DateTime(Immutable)::setTime with $microseconds

- standard/memcache.php
* Fixed parameter signature for `memcache_connect`
* Added docblock parmaeter descriptions
* See https://youtrack.jetbrains.com/issue/WI-32913#u=1471550512213
> Fixed parameter signature for `memcache_connect` 

- standard/memcache.php
It seems that the add documentation was copied and pasted from the addServer documentation, and a few things were forgotten. This PR changes that to match that of http://www.php.net/manual/en/memcache.add.php with a small amount of extra details.
> Fix incorrect documentation for Memcache::add

- standard/PDO.php
We extend PDOStatement and override the execute method. We noticed that the suggested method signature does not match the actual method signature.
PhpStorm shows the signature as:
`public function execute (array $input_parameters = null)`
The actual method signature is:
`public function execute ($input_parameters = null)`
PHP version:
`PHP Version => 7.0.15-1+deb.sury.org~trusty+1`
> PDOStatement execute method signature update

- standard/standard_8.php
In the new PHPStorm 2017.1 EAP this change is needed to use this function with one parameter only. In PHPStorm 2016.3.2 the parameter is recognized as optional without this change.
> getimagesizefromstring: mark 2nd parameter as optional

- Reflection/Reflection.php
Almost all constructors throw a ReflectionException, but they are not annotated and sometimes not even mentioned in the manual. I added the appropriate @throws annotation to every constructor.
> Added @throws annoations to reflection constructors

- SPL/SPL_c1.php
SplFixedArray method setSize does not return an integer, but returns boolean as tested using PHP version 5.3 to 7.0, even though the PHP documentation states otherwise.
> SplFixedArray method setSize does not return an integer

- Core/Core.php
- mcrypt/mcrypt.php
- standard/standard_8.php
> WI-33334 mcrypt - extend WI-24248 Allow usage of ArrayObject in place of array for array_* functions

- SPL/SPL.php
As according to the PHP doc: http://php.net/manual/en/arrayobject.construct.php
ArrayObject 1st parameter $input is default an empty array, not null.
> ArrayObject construct input default is empty array, not null

- curl/curl_d.php
- `CURLOPT_HTTP_VERSION_2_0` doesn't exist, it is `CURL_HTTP_VERSION_2_0` but it's missing from the PHP documentation
- `CURLOPT_HTTP_VERSION_2TLS` and `CURLOPT_HTTP_VERSION_2_PRIOR_KNOWLEDGE` were introduced along `CURLOPT_HTTP_VERSION_2` but were missing.
> Fix missing cURL constants

- mongodb/mongodb.php
according to php menu, the construct function should accept null;
http://php.net/manual/en/mongodb-bson-utcdatetime.construct.php
> update UTCDateTime construct method

- standard/_types.php
Docs states it must return array and if void returned, then it's serialized as null and notice issued.
Returned array contains field names to include in serialization, so it's array of strings.
http://php.net/manual/en/language.oop5.magic.php#language.oop5.magic.sleep
> Change __sleep signature

- date/date_c.php
- DatePeriod has 6 undocumented properties
- getEndDate() can also return null.
See https://bugs.php.net/bug.php?id=74176 and https://3v4l.org/kSsIo
> Add missing DatePeriod properties and fix getEndDate return type.

- mbstring/mbstring.php
The default value for `$offset` is `0` according to the documentation:
- [mb_strpos](http://php.net/manual/en/function.mb-strpos.php)
- [mb_strrpos](http://php.net/manual/en/function.mb-strrpos.php)
- [mb_stripos](http://php.net/manual/en/function.mb-stripos.php)
- [mb_strripos](http://php.net/manual/en/function.mb-strripos.php)
The current default value of `null` in the stubs is misleading: when you want to skip the offset but provide the `$encoding` parameter, you're tempted to pass `null` when you should be passing `0`.
> Fix default values for mb_str*pos()

- Reflection/Reflection.php
PHP 7.1 introduced ReflectionType::getName as alternative for __toString.
__toString deprecated and will be removed in PHP 8.0 (see php/php-src#2137 (comment))
Added getName() stub and marked __toString as deprecated.
(and removed some trailing whitespace)
> Add stub for ReflectionType::getName

- standard/standard_2.php
Fixed default signal value of proc_terminate which is 15, not null. As per http://php.net/manual/en/function.proc-terminate.php#refsect1-function.proc-terminate-description
> Fixed default signal value of proc_terminate

- PDO/PDO.php
The return type should be `mixed`, not `string`. In particular, it returns `false` when there are no more rows.
See: http://php.net/manual/en/pdostatement.fetchcolumn.php
> Fix PDOStatement::fetchColumn() return type

- mongo/mongo.php
MongoClient requires mixed not only arrays for hints. Throwing warnings all over the codebase.
> Changed MongoCursor.hint `key_pattern` from array to mixed

- standard/_types.php
I often type `__` in class body to produce some base method like constructor.
If I use method from completion list then I have to provide visibility each time.
I think default `public` visibility should be there as these methods are public by default.
> Set default visibility for object class methods

- standard/standard_1.php
http://php.net/manual/en/function.setlocale.php
$locale can be array of locales
> setlocale() fix: $locale allows array

- standard/standard_8.php
> If the internal pointer points beyond the end of the elements list or the array is empty, key returns null
Sorry I missed that in #232.
> Update key() return type

- mbstring/mbstring.php
- openssl/openssl.php
- tokenizer/tokenizer.php
Fixed $option default value mb_ereg_replace() and mb_ereg_replace()
Added missing parameters to openssl_encrypt() openssl_decrypt()
WI-37444 Invalid stub for token_get_all php 7.0
> Fixed mb_ereg_replace() mb_ereg_replace() openssl_encrypt() openssl_decrypt() token_get_all() descriptions

- pcre/pcre.php
added missing `FALSE` as a return value for `preg_split` if error occurs
http://php.net/manual/en/function.preg-split.php
> preg_split doc update

- json/json.php
Hi. I was wondering why `jsonSerialize()` has no visibility defined. Every developer I know always adds it manually after adding method stubs.
> Add visibility for jsonSerialize() in JsonSeializable interface

- standard/standard_3.php
Unable to make a parameter its own absolute value with the current number annotation.  There'll be an issue with this request soon.
> Change abs return value to actual PHP types

- standard/standard_9.php
Looks like the `array_flip` return value should be `array|null` rather than `array|bool`.
Link to the docs [here](http://php.net/manual/en/function.array-flip.php).
> array_flip return value fix

- sodium/sodium.php
This pull request adds the new `sodium_*` syntax of [php-libsodium 2.*](https://github.com/jedisct1/libsodium-php#libsodium-php-1x-vs-libsodium-php-2x) and also what the future [PHP 7.2 functions will be named](https://wiki.php.net/rfc/libsodium).
Note: This does **NOT** get rid of libsodium stubs (older versions of PHP)
> Adding "Sodium" (new libsodium and PHP 7.2 feature)

- standard/standard_4.php
Change parameter from string to callable. This makes unregister_tick_function match register_tick_function.
See https://youtrack.jetbrains.com/issue/WI-37754
> Change phpdoc for unregister_tick_function

- intl/intl.php
- oci8/oci8.php
- standard/standard_3.php
- standard/standard_8.php
Inspired by #256, I replaced `number` type to `int|float` in all stubs.
Php documentation uses `number` to denote `int|float`: http://php.net/manual/en/language.pseudo-types.php#language.types.number
> Replace number type with int|float

- mongo/mongo.php
Currently the mongo.php stub defines a MongoGridFS::__get method which is actually MongoCollection's method but does not define the real get method.  This just changes the name of __get to get.
See: https://youtrack.jetbrains.com/issue/WI-37636
> Change MongoGridFS::__get to get

- SimpleXML/SimpleXML.php
The actual array access methods are not available, but the internal class implements the equivalent C-level handlers, so that [0], ['foo'], etc are always available. 
This removes the need to mark any returns as SimpleXMLElement[], except for ->xpath(), which really does return a true array.
Issue was reported in 2012: https://youtrack.jetbrains.com/issue/WI-15760 This solution is not ideal, but the stub already contains a dummy __get(), so this seems a logical improvement.
> Add dummy ArrayAccess to SimpleXMLElement to fix WI-15760

- Core/Core.php
PhpStorm can't navigate to callables, because of wrong typehints on following functions:
- restore_error_handler
- set_exception_handler
> Fix callable typehints

- redis/Redis.php
Most important thing here is that the `delete()` function currently incorrectly reports `void` return type. The signatures of both functions should be the same, and keys are of type `string`.
> WI-38016 fix redis del() and delete() docs

- mongodb/mongodb.php
The parameter $flags for the class MongoDB\BSON\Regex is optional:
http://php.net/manual/en/mongodb-bson-regex.construct.php
> Flags parameter in Regex constructor is optional

- zip/zip.php
Added 2 missing methods ( `setEncryptionIndex ` , `setEncryptionName ` ) to ZipArchive
> Added missing methods to ZipArchive

- intl/intl.php
`IntlDateFormatter::formatObject` is actually a static method:
http://www.php.net/manual/en/intldateformatter.formatobject.php
> [Intl] Made IntlDateFormatter::formatObject static method

- mongodb/mongodb.php
As per https://github.com/mongodb/mongo-php-driver/pull/640, `MongoDB\BSON\ObjectID` has been renamed to `MongoDB\BSON\ObjectId` in 1.3.0.
The change should not cause problems for people on versions prior to the change, as PHP doesn't check case for classes declared in extensions.
> Rename MongoDB\BSON\ObjectID to ObjectId

- date/date_c.php
PHP 7.2 compatibility after PHP request #71520 [implemented](https://github.com/php/php-src/pull/2483) by @Majkl578.
> Move DateTime constants to DateTimeInterface

- mysqli/mysqli.php
Fixes WI-38808
https://youtrack.jetbrains.com/issue/WI-38808
http://php.net/manual/en/mysqli.commit.php
> Update mysqli commit() to include optional params per PHP documentation 

- standard/standard_9.php
- Correct the default value for PHP stub `array_unique()` parameter `$sort_flags`
- Update list of Sorting type flags accepted by `array_unique()` to match PHP documentation
- [WI-38863](https://youtrack.jetbrains.com/issue/WI-38863)
> Update PHP stub for array_unique

- mongodb/mongodb.php
It was added to library but then removed as unused.
See https://github.com/mongodb/mongo-php-driver/commit/95774b10d2f8ec6c4ccedb71f9d9b7ca3cdc8c86 and https://github.com/mongodb/mongo-php-driver/commit/15a9f709d279bf49094f33deb74e4de49e078791.
> WI-39019: remove DuplicateKeyException

- ssh2/ssh2.php
Fix WI-38956 Lack of ssh2_sftp_chmod definition in phpstorm-stubs
Add `ssh2_sftp_chmod`, `ssh2_auth_agent`.
> WI-38956 Lack of ssh2_sftp_chmod definition in phpstorm-stubs

- session/SessionHandler.php
This interface is not documented on php.net, the only [documentation](https://github.com/php/php-src/blob/f9c3ee9ae8a41e2f47101c638491abd36ed09ce3/ext/session/session.c#L2730) is the code itself. There is also a [polyfill from Symfony](https://github.com/symfony/polyfill/blob/ff0c49221c6ef38caa463b182c17f2513f35c8ea/src/Php70/Resources/stubs/SessionUpdateTimestampHandlerInterface.php).
Is a documentation on php.net needed to get this merged?
> Add stub for SessionUpdateTimestampHandlerInterface

- sockets/sockets.php
The PHP source code shows that the method socket_cmsg_space has a third argument.
See PHP source: ext/sockets/sendrecvmsg.c:278
> WI-39334 | Third argument for socket_cmsg_space

- xmlwriter/xmlwriter.php
https://secure.php.net/manual/en/function.xmlwriter-write-cdata.php
The names are spelled differently, and thus I fixed it.
> fix spelling mistake in xmlwriter

- sodium/sodium.php
This function may return `false` on failure.
> Fixed sodium.sodium_crypto_secretbox_open() stub

- soap/soap.php
The recent change to expose the semi-public properties of SoapFault is a good thing.  
I know that http://php.net/manual/en/class.soapfault.php shows $details and $headerfault as strings but they're zvals in the engine
```
soap.c
/* {{{ proto object SoapFault::SoapFault ( string faultcode, string faultstring [, string faultactor [, mixed detail [, string faultname [, mixed headerfault]]]])
if (zend_parse_parameters(ZEND_NUM_ARGS(), "zs|s!z!s!z",
&code,
&fault_string, &fault_string_len,
&fault_actor, &fault_actor_len,
&details, &name, &name_len, &headerfault) == FAILURE) {
return;
}
```
and being declared as string in the stub causes PhpStorm to raise invalid issues while inspecting "correct" code.
```
/**
* populate error response
*
* @param SoapFault $soapfaultObj
* @param array …
```
> Changed detail and headerfault from string to mixed

- imagick/imagick.php
Note that the previous stub is accurate for PHP Imagick `>=2.0.0 && <2.2.0`, I'm not sure if there's a way to denote that or not, but either way the stub is 10 years out of date.
> Fixed imagick.getImageProfiles stub

- standard/standard_8.php
For https://youtrack.jetbrains.com/issue/WI-22258
The array iterator functions end, prev, next, reset, current, and key are all written to accept an array or an object instance
```
/* {{{ proto mixed current(array array_arg)
Return the element currently pointed to by the internal array pointer */
PHP_FUNCTION(current)
{
HashTable *array;
zval *entry;
#ifndef FAST_ZPP
if (zend_parse_parameters(ZEND_NUM_ARGS(), "H", &array) == FAILURE) {
return;
}
#else
ZEND_PARSE_PARAMETERS_START(1, 1)
Z_PARAM_ARRAY_OR_OBJECT_HT(array)
ZEND_PARSE_PARAMETERS_END();
#endif
```
From http://php.net/manual/en/internals2.funcs.php
```
H | array or object | HashTable*
```
Even though the {{{ proto and http://php.net/manual/en/function.current.php claim it only takes an array.
> Change ArrayObject to object in PHPDoc for array iterator functions.

- xmlreader/xmlreader.php
The php.net site (as referred to in the annotations) uses readInnerXML and readOuterXML.
http://php.net/manual/en/xmlreader.readinnerxml.php
http://php.net/manual/en/xmlreader.readouterxml.php
I noticed this when running phpstan.
> Case mismatch in two XMLReader methods

- Reflection/Reflection.php
[PHP documentation][1] also gets it wrong, as suggested by the [engine source][2]
[1]: http://php.net/manual/en/reflectionclass.setstaticpropertyvalue.php
[2]: https://github.com/php/php-src/blob/12c386f5b90387ce373e16cdf74fd4d3155d5aa7/ext/reflection/php_reflection.c#L3904
Resolves https://youtrack.jetbrains.com/issue/WI-39719
> Fix ReflectionClass::setStaticPropertyValue signature

- solr/Utils/SolrUtils.php
The type has been added according to the documentation on: http://php.net/manual/en/solrutils.queryphrase.php
```
public static string SolrUtils::queryPhrase ( string $str )
```
> Added a missing @return type for SolrUtils::queryPhrase()

- memcache/memcache.php
trouble case:
```
class MyFooMemcache extends \Memcache {
public function get($key, &$flags){} //this is actual stub's signature
}
```
turns into warning:
```
Missing argument 2 for MyFooMemcache::get()
```
> Optionality of params fix in methods signatures

- mailparse/mailparse.php
Documentation from http://php.net/manual/en/book.mailparse.php
PECL package: http://pecl.php.net/package/mailparse
Inspired by the recent blog post! I've had this included into my projects as an external library for a couple of years, it would be nice to see it included in the standard set.
I hope I've got the formatting correct!
> Add stubs for PECL mailparse

- standard/standard_0.php
This has messed up the HTML table ...
... and the table with the constants itself was not shown.
> Fixed HTML table in PhpDoc for htmlspecialchars

- Core/Core_c.php
`ArgumentCountError`  should extends `TypeError`
`DivisionByZeroError` should extends `ArithmeticError`
Please see
* http://php.net/manual/en/class.argumentcounterror.php
* http://php.net/manual/en/class.divisionbyzeroerror.php
* https://3v4l.org/f8Boe#output
Issue
* https://youtrack.jetbrains.com/issue/WI-41073
> Fixed ArgumentCountError DivisionByZeroError extends (WI-41073)

- PDO/PDO.php
**Changes**
* Added alternative return types.
* Added missing docs to some PDO Constants.
* Changed see section **texts** to see **tags**
* Added anchors to all links of constant docs links.
* Added missing types to some params.
* Converted available since **texts** to since **tags**.
* Added PHP 7 to version indicators such as `(PHP 5 >= 5.1.3, PHP 7, PECL pdo >= 1.0.3)`.
Maybe some of identation accidentaly messed up or even fixed.:blush: Sorry for that.
[YouTrack Issue #WI-40876](https://youtrack.jetbrains.com/issue/WI-40876)
> General Improvements for PDO

- apc/apc.php
The lack of "php" here causes some configurations to interpret the file as non-php.
> Changing "<?" to "<?php" in apc/apc.php

- libsodium/libsodium.php
- sodium/sodium.php
- standard/_standard_manual.php
This change required to parse functions PHPDocs by phpdocumentor/reflection-docblock parser.
> Make PHPDocs PHPDoc parser compatible

- uopz/uopz.php
I noticed PhpStorm doens't know about the `uopz` extension, this PR adds support for it.
Extension information from PECL:
https://pecl.php.net/package/uopz
PHP.net documentation:
http://php.net/manual/en/book.uopz.php
> Add stubs for the uopz extension

- standard/standard_2.php
According to the official PHP documentation and actual behaviour the return type of shell_exec can be null if an error occurred or the command did not produce any output.
* See http://php.net/manual/en/function.shell-exec.php
> Fix return type of shell_exec which can be null

- soap/soap.php
See php.net: http://php.net/manual/en/soapclient.call.php
> Updated SoapClient::__call() $arguments type to array

- standard/standard_7.php
`glob()` returns `false` on error ([docs](http://php.net/glob))
Using `array|false` (instead of `array|bool`) according to the discussion at #385 
Edit: opened a new PR since #385 got approved, and I didn't want to "disturb" it. I can update that one instead, if needed.
> Updated return type for glob()

- standard/standard_6.php
* Official documentation says it can return int or false on failure
* See http://php.net/manual/en/function.stream-copy-to-stream.php
> Fix return type and description of stream_copy_to_stream

- standard/standard_8.php
Some of the inspection plugins (e.g. EA Extended) will emit a warning if the type casting is not necessary, which will generate false warning in cases for the signatures updated here, like this one:
Function descriptions already contain "... or false if ...", just the type itself does not include it.
~Also, `false` is a valid return type to use, but I've noticed that just `bool` is used in other similar cases, hence `string|bool` here, too. I'd prefer `string|false` though, because `true` will never be returned.~
Edit: amended the commit to use `string|false`.
> Updated return types for some of the ob_ functions

- zip/zip.php
In PHP 7.2, new ZIP encryption constants were added that haven't been reflected in this file. These are:
- EM_NONE
- EM_AES_128
- EM_AES_192
- EM_AES_256
(please refer to http://php.net/manual/en/zip.constants.php).
These have now been added with relevant link and since tags.
> Added ZIP Encryption constants

- standard/standard_1.php
The second param `$is_xhtml` default value is `true` not `null`
[Source PHP Docs](https://secure.php.net/manual/en/function.nl2br.php)
> Update nl2br function

- shmop/shmop.php
[shmop_open()](http://php.net/manual/en/function.shmop-open.php) returns a resource, and then all the other `shmop_` functions expect a resource, not an integer
> Correct the type of shared memory identifiers

- com_dotnet/com_dotnet.php
When using e.g. `\COM`, an inspection warns about `ext-com` missing from `composer.json`.
However, `composer require ext-com` fails:
This is because the library is actually called `com_dotnet`, not `com`:
(Source: https://secure.php.net/manual/de/com.installation.php)
> Fixes the "com_dotnet" extension name

- curl/curl.php
The return type of `curl_exec()` right now is `mixed`, which is very unspecific, as it could be anything - an array, an object, a string, a float, just anything. But in fact, `curl_exec()` can only return `string|bool` (depending on the passed setting `CURLOPT_RETURNTRANSFER`), but never things like an array or an object.
> Specify return type of curl_exec() further

- SPL/SPL_c1.php
The method `SplFileInfo::getRealPath()` can return `false` in case the file does not exist.
See https://secure.php.net/manual/en/splfileinfo.getrealpath.php .
> Fix return type of SplFileInfo::getRealPath()

- intl/intl.php
The description for the return type is already correct, but the annotation isn't: `idn_to_utf8()` can return either a string or false in case of an error.
> Fix return type of idn_to_utf8()

- redis/Redis.php
It can be used as usual \Redis instance: https://github.com/phpredis/phpredis/blob/master/arrays.markdown#usage
> Improve \RedisArray typehinting

- date/date_c.php
As of now, the PHP documentation still says it is a DateTime, but testing confirms both DateTime and DateTimeImmutable work.
> DateTimeZone getOffset method accepts DateTimeInterface instead of DateTime

- password/password.php
See https://wiki.php.net/rfc/argon2_password_hash_enhancements
Ref https://youtrack.jetbrains.com/issue/WI-44284
> [WI-44284] Add PASSWORD_ARGON2ID constant (PHP 7.3)

- intl/intl.php
See [WI-44078](https://youtrack.jetbrains.com/issue/WI-44078) (with expanded scope of updating/fixing/expanding the docs for the entire class). The docs on the PHP site are rather incomplete, so missing info was derived from the [ext/intl/timezone](https://github.com/php/php-src/tree/master/ext/intl/timezone) source code.
> intl: update IntlTimeZone

- oci8/oci8.php
When analyzing the code using `oci8` with PHPStan, some existing stubs cause [false positive issues](https://phpstan.org/r/4d4967ac-46e6-4f1f-a0c7-bfc533ddaaa5).
> Made return types of the oci8 functions more accurate

- standard/standard_9.php
The return type for `array_combine()` is either `array` or `false`. Actually, the description is correct, just the declared return type is wrong.
> Fix return type for array_combine()

- redis/Redis.php
Method exists returns a number since version 4. Actual docs - https://github.com/phpredis/phpredis#exists
> Change return type for Redis::exists to int

- intl/intl.php
According to docs (https://secure.php.net/manual/en/messageformatter.formatmessage.php)
```
string msgfmt_format_message ( string $locale , string $pattern , array $args )
```
> msgfmt_format_message takes only 3 args

- ibm_db2/ibm_db2.php
Similarly to https://github.com/JetBrains/phpstorm-stubs/pull/455, when analyzing the code using `ibm_db2` with PHPStan, some existing stubs cause [false positive issues](https://phpstan.org/r/4d4967ac-46e6-4f1f-a0c7-bfc533ddaaa5).
Additionally, `[optional]` markers have been removed from parameter annotations since they are redundant, non-standard and may conflict with the `[]` ones. Also, parameter annotations like `@param variable type` have been converted to `@param type $variable` for compliance with phpDoc.
Despite the fact that the `$value` argument of `db2_autocommit()` is [documented](https://secure.php.net/manual/en/function.db2-autocommit.php) as boolean, it accepts one of the `DB2_AUTOCOMMIT_*` constants which are integer. The method signature has been modified to avoid false …
> Made return types of ibm_db2 functions more accurate

- Reflection/Reflection.php
Although not properly documented [on the php.net website](http://php.net/manual/en/reflectionclass.getproperty.php) (only in the comments section), `ReflectionClass::getProperty()` throws a `ReflectionException` when the property does not exist:
```php
class A {}
(new ReflectionClass('A'))->getProperty('B'); // ReflectionException: Property B does not exist
```
Demo [here](https://3v4l.org/JOobg).
> Add missing @throws in ReflectionClass::getProperty()

- Core/Core.php
- Core/Core_c.php
- PDO/PDO.php
- SPL/SPL_c1.php
- curl/curl_d.php
- date/date_c.php
- docker-compose.yml
- filter/filter.php
- mbstring/mbstring.php
- openssl/openssl.php
- pcre/pcre.php
- standard/standard_4.php
- standard/standard_5.php
- zlib/zlib.php
WI-42885 Update stubs for PHP 7.3 WI-44764 net_get_interfaces missing from phpstorm-stubs (PHP 7.3)
> PHP 7.3 stubs update

- fpm/fpm.php
This function is not officially documented, yet. But it definitely returns an array. :)
See: https://github.com/php/php-src/pull/3182
> Fix missing return type of fpm_get_status() function

- Reflection/Reflection.php
According to php.net
https://secure.php.net/manual/en/reflectionclassconstant.ispublic.php
The method isPublic do not take params and return a bool. Seems like a typo.
> fix phpdoc

- PDO/PDO.php
These exceptions are all documented in the PHP Manual.
https://secure.php.net/manual/en/class.pdo.php
Fixes the first part of https://youtrack.jetbrains.com/issue/WI-8146, which was wrongly closed as a duplicate.
> Add missing PDO exceptions

- mysqli/mysqli.php
1. Added missing `|false` to some function which can return `false`.
2. For functions which return `true` but don't return `false`, replaced `bool` with `false` since the former implies `true` is also possible.
3. [`mysqli_get_client_version()`](http://php.net/manual/en/mysqli.get-client-version.php#refsect1-mysqli.get-client-version-returnvalues) returns the version ID as an `int`, not as a `string`.
4. [`mysqli_stmt_errno()`](http://php.net/manual/en/mysqli-stmt.errno.php#refsect1-mysqli-stmt.errno-returnvalues) returns the error code, not a `bool`.
> Made return types of mysqli functions more accurate

- session/session.php
you see the cast to int seems unnecessary but that indication is false because the function returns false is no sessions were deleted
> Correct session_gc signature

- standard/standard_7.php
Skimmed through all stubs in the `standard/standard_7.php` file and updated the phpdocs to ensure the `@return` tag accurately reflected the types of any error values that could be returned (e.g. **FALSE** or **NULL**).
See [WI-44450](https://youtrack.jetbrains.com/issue/WI-44450)
> Fix return types in standard_7.php stubs

- hash/hash.php
Set optional params of hash_pbkdf2 as optional correctly.
http://php.net/manual/en/function.hash-pbkdf2.php
> Fixed optional in hash_pbkdf2 declaration

- SPL/SPL_c1.php
Hi,
SplFileObject::current() can return false if the pointer is out of bounds.
This is not mentionned in the php.net website, but here's a reproducible code:
https://3v4l.org/6XefC
Thanks
> SplFileObject::current() can return false

- SPL/SPL_c1.php
The official php-documentation was even incorrect at this point as
shown in https://3v4l.org/X3h8Q
Insert returns true when successfull. It is unclear if it can ever
return false.
> Set correct return type for insert method

- zip/zip.php
The error return codes where mentioned in the comment, but not part of the parsed return type. This PR changes this for tie `zip`-stub.
> Fix error returns

- redis/Redis.php
Type hints required array, but the real allowed values are "array" or "...string", which is impossible to add using real PHP type hints since variadic params are only allowed if they're the final parameter.
> Clarify type hints for Redis::blPop and brPop

- dom/dom_c.php
Reverts JetBrains/phpstorm-stubs#503
The return type is actually `DOMElement`: https://3v4l.org/4Z5oj
> Revert "DOMNodeList::item() returns DOMNode instead of DOMElement"

- meta/.phpstorm.meta.php
*see change*
... or is there any reason for this?
> Duplicate line for ArrayObject::__construct in .phpstorm.meta.php

- date/date_c.php
Links were changed to use https without updating the url to be secure.php.net, causing the links to be broken.
> Fix broken https php.net links

- mbstring/mbstring.php
The "$part" parameter is incorrectly named and defines an incorrect default value (null) for haystack/needle mbstring functions.  Correct name is $before_needle and value is false.
> Correct naming and default value of mbstring $before_needle params

- standard/standard_2.php
The third option of strchr which is an alias of strstr is optional and not providing the default value causes incorrect syntax warnings.
> strchr optional third argument

- standard/standard_6.php
Marks the final parameter for `get_headers()` as optional.
> Fix optional parameter for get_headers()

- redis/Redis.php
- redis/RedisCluster.php
PHP 7.2 + phpstan complains when the value is type hinted to a string as it states it can only accept an int or an array
> CHANGED param types for Redis to satisfy phpstan

- meta/.phpstorm.meta.php
According to documentation there is no value `2` for `ob_implicit_flush`. Only `0` and `1` are allowed:
https://www.php.net/manual/en/function.ob-implicit-flush.php
> Fix expected arguments for ob_implicit_flush

- memcached/memcached.php
Returns `array` and not `bool`.
See https://www.php.net/manual/en/memcached.deletemulti.php#refsect1-memcached.deletemulti-returnvalues
> Update Memcached::deleteMulti return type and description

- mbstring/mbstring.php
*see changes*
Sources:
https://php.net/manual/en/mbstring.constants.php
https://php.net/manual/en/migration73.new-features.php#migration73.new-features.mbstring.case-mapping-folding
> Add PhpDoc for MB_CASE_ constants since PHP 7.3

- meta/.phpstorm.meta.php
It's very common to have `__DIR__` and `__FILE__` as arguments for `dirname()`. 
(Getting current directory or parent directories)
This also uses `expectedReturnValues` as a trick, so `dirname()` gets listed when calling it nested:
`dirname(dirname(dirname(__DIR__)))`
Also you get completion in comparison for `__DIR__`:
```php
if (dirname($file) == <caret>) { ...
```
> Add expectedArguments common for dirname

- Core/Core.php
`user_error` is lacking the default `E_USER_NOTICE` that `trigger_error` already has.
> Update user_error stub to match trigger_error

- standard/standard_defines.php
Added `@since` tags instead of plain text description for some standard defines.
> Add "since" PhpDoc tags for standard defines

- Parle/Parser.php
- Parle/RParser.php
The type declaration on this argument should be int instead of array, unfortunately I ran into the following error:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Parle\Parser::sigil() must be of the type integer, array given
```
I've submitted a patch to amend the documentation over at https://www.php.net/manual/en/parle-parser.sigil.php and https://www.php.net/manual/en/parle-rparser.sigil.php.
Please let me know if there are any issues.
> Correct type declaration

- standard/standard_9.php
The function `cli_get_process_title` and `cli_set_process_title` are already defined in `basic.php` and as such I've removed them from `standard_9.php`. If you prefer it to be the other way around, raise your voice.
> Remove double definition

- standard/standard_4.php
Is there any reason for these strange tags?
Otherwise we can remove them, because they show up in PhpStorm Quick Doc:
> Remove possible formatting left-overs from PhpDocs

- SimpleXML/SimpleXML.php
If `xpath` is called from `SimpleXMLIterator`, which extends `SimpleXMLElement`, the result type of `xpath` would be `SimpleXMLIterator[]`, not `SimpleXMLElement[]`. Currently, Phpstorm would report non-existing `current`/`next`/`rewind` methods that are called on `xpath` results even if the underlying type is `SimpleXMLIterator` (which has those methods). A simplest fix is to annotate return type as `static[]`, because this way Phpstorm is able to infer proper type of the elements and stops making false reports about undefined methods.
Simple example that demonstrates that:
```php
<?php
$strXml= <<<XML
<a>
<b>
<c>text</c>
<c>stuff</c>
</b>
<d>
<c>code</c>
</d>
</a>
XML;
// $xml = new SimpleXMLElement($strXml, 0);
// $root = $xml->xpath("/a");
// var_dump($root);
$xml = new …
```
> SimpleXML: better return annotation for xpath

- date/date.php
I think this should be optional and default to the value returned by `time()`: https://www.php.net/manual/en/function.strftime.php
> make strftime() $timestamp optional

- com_dotnet/com_dotnet.php
This class doesn't have a manual page in the traditional format (see https://php.net/manual/en/com.error-handling.php).
Several other classes appear when writing `php --re com_dotnet`, but I did not take the time to investigate those.
> added missing com_exception to com_dotnet stub

- gmp/gmp.php
GMP transitioned to objects in PHP 5.6, which was not reflected by the stub, causing false positives wherever it was used.
> Fixed GMP stub for PHP >= 5.6

- xmlrpc/xmlrpc.php
xmlrpc_server_register_method third argument is any kind of callable:
-  `array($bar, "foo_func")`
> xmlrpc_server_register_method: use callable type

- rdkafka/RdKafka/Message.php
Ran into this today, thought this was already on the stub, found out it wasn't so PRing it to be added.
> Add ext-rdkafka missing timestamp on Message

- xdebug/xdebug.php
https://xdebug.org/docs/all_functions#xdebug_stop_code_coverage
While even the documents list "false" as an appropriate option, running this with `strict_types` enabled requires an int value.
> Update xdebug_stop_code_coverage parameter

- soap/soap.php
Storm complains when the correct method signature is in place. Using the stub's signature throws a warning in the `error_log`, so I updated the method signature.
Please see https://youtrack.jetbrains.com/issue/WI-47198
> fixing __soapCall() method signature

- curl/curl.php
According to [the docs](https://www.php.net/manual/en/function.curl-multi-select.php), the second parameter has a default value of `1.0`.
> Fix default curl_multi_select() value

- Reflection/Reflection.php
`ReflectionType::getName()` method doesn't exist [1][2], it's ReflectionNamedType::getName() instead [3].
[1] https://php.net/reflectionType
[2] https://3v4l.org/EgCmC
[3] https://www.php.net/manual/en/reflectionnamedtype.getname.php
> ReflectionType::getName() should be ReflectionNamedType::getName()

- json/json.php
Reverts JetBrains/phpstorm-stubs#632
We have to revert the change since it produces a lot of false positives on popular frameworks.
We have to wait till the solution for https://youtrack.jetbrains.com/issue/WI-45642 is found.
> Revert "json encode/decode throws JsonException when JSON_THROW_ON_ERROR is set"

- standard/standard_8.php
[array_unshift()](https://www.php.net/manual/fr/function.array-unshift.php) has been there since PHP 4.
It's only the possibility of calling the function with a single argument that has been introduced in PHP 7.3.
> array_unshift() has not been introduced in PHP 7.3

- dom/dom_c.php
Although this is not specified on the `item()` documentation page itself, it is specified here:
https://www.php.net/manual/en/class.domnodelist.php
> length
> The number of nodes in the list. The range of valid child node indices is 0 to length - 1 inclusive.
It's important that it's part of the `item()` doc IMO. I was myself looking for this information just now.
> Specify that DOMNodeList::item() indexes are 0-based

- grpc/grpc.php
The first parameter of `Grpc\ChannelCredentials::createSsl` is currently required according to the stubs but this conflicts with the grpc extension.
If you look at the reflection information using something like:
```php
<?php
use Grpc\ChannelCredentials;
$method = new \ReflectionMethod(
ChannelCredentials::class,
"createSsl"
);
foreach ($method->getParameters() as $parameter) {
$attr = $parameter->isOptional()
? ' (optional)'
: '';
printf("%s\n", $parameter->getName() . $attr);
}
```
All parameters are marked as optional.
```
pem_root_certs (optional)
pem_private_key (optional)
pem_cert_chain (optional)
```
You can also see that in the source, of course.
https://github.com/grpc/grpc/blob/99af46ca647efa10581c08579d13101fe30e1345/src/php/ext/grpc/channel_credentials.c#L135-L136
> Grpc\ChannelCredentials::createSsl() has all optional parameters.

- sockets/sockets.php
When you import this function using
```php
use function socket_export_stream;
```
PhpStorm says this:
> Fixed stub for socket_export_stream function

- mongodb/mongodb.php
According to https://www.php.net/manual/en/mongodb-driver-monitoring-commandstartedevent.getcommand.php, it returns an object
> [mongodb] Fix CommandStartedEvent::getCommand() return type

- Reflection/Reflection.php
The [typed properties RFC](https://wiki.php.net/rfc/typed_properties_v2) (accepted, implemented in PHP 7.4.0, currently beta2) introduces 3 new reflection methods:
```php
class ReflectionProperty {
// ...
public function getType(): ?ReflectionType;
public function hasType(): bool;
public function isInitialized([object $object]): bool;
}
```
Even though these are not in the PHP manual yet, they will be soon, and it would be nice to get PHPStorm support right now.
Test script:
```php
class Test {
public $foo;
public int $bar;
}
$test = new Test;
$foo = new ReflectionProperty('Test', 'foo');
var_export($foo->hasType()); // false
var_export($foo->getType()); // NULL
var_export($foo->isInitialized($test)); // true
$bar = new ReflectionProperty('Test', 'bar');
var_export($bar->hasType()); // …
```
>  Support for typed properties in ReflectionProperty

- rdkafka/RdKafka/Message.php
Source code that proves that this property exists:
- https://github.com/arnaud-lb/php-rdkafka/blob/546e17eb04ae6/message.c#L157
- https://github.com/arnaud-lb/php-rdkafka/blob/546e17eb04ae6/message.c#L63
> Add missing Rdkafka\Message::$len property

- standard/standard_5.php
The default of the second parameter of intval was always 10.
Documentation:
https://www.php.net/manual/en/function.intval.php
Example: 
https://3v4l.org/qj37f
> Updating default value of intval 2nd parameter

- mongodb/mongodb.php
adding @throws to the mongodb/Manager::executeBulkWrite
According to docs this method actually throws exceptions
https://www.php.net/manual/en/mongodb-driver-manager.executebulkwrite.php
> add @throws to the mongodb

- Core/Core.php
- Core/Core_d.php
- tests/TestData/mutedProblems.json
Updates the value for E_ALL, multiple places. Adds others to the list a for `get_defined_constants()`.
Closes WI-39737
> Update - Stubs: Out of date definition for E_ALL.

- solr/Queries/SolrQuery.php
Add `null` as return type where it is returned according to documentation.
Fix return type of SolrQuery::getFacetDateOther, as per https://github.com/php/doc-en/commit/53c73366ac7bb67f168a3b35491c14a382cf470a
> Fix/update SolrQuery return types

- ftp/ftp.php
Default value for transfer mode was missing from function headers.
> Add default parameter values for ftp_* functions

- mbstring/mbstring.php
Hello,
this PR added missing fourth function argument `is_hex`. Reference to PHP doc https://www.php.net/manual/en/function.mb-decode-numericentity.php
> Added missing optional argument for mbstring function

- standard/standard_1.php
`explode()` does not return array in all cases. It returns `false` for empty delimiter. Also `array` is to generic, in fact `explode()` returns an array of strings.
> explode() returns false or array of strings

- soap/soap.php
Hi,
[Manual](https://www.php.net/manual/en/soapvar.soapvar.php) describe $encoding as:
> The encoding ID, one of the XSD_... constants.
According to https://www.php.net/manual/fr/soap.constants.php
All XSD constants types are integer.
However, the value of XSD_NAMESPACE and XSD_1999_NAMESPACE are respectively http://www.w3.org/2001/XMLSchema and http://www.w3.org/1999/XMLSchema which contradicts the manual because such value can't be stored in integers
What's strange is that the [Manual](https://www.php.net/manual/en/soapvar.soapvar.php) says that $encoding is string only.
It should be string|int at the very least.
Thanks
> Fix SoapVar::__construct $encoding type

- session/session.php
Since PHP 7.3, an additional signature (with an `$options` parameter) is available for `session_set_cookie_params()`.
https://www.php.net/manual/en/function.session-set-cookie-params.php
> Add new session_set_cookie_params signature

- dom/dom_c.php
- meta/.phpstorm.meta.php
Changed some methods to return correct type instead of `DOMNode` in all cases.
> DOMDocument return types

- meta/.phpstorm.meta.php
`iterator_to_array` returns array, not type from parameter.
> iterator_to_array remove override

- meta/.phpstorm.meta.php
`elementType(0)` have no connection with returned value, last parameter *should* be correct return type if present.
https://www.php.net/manual/en/function.array-reduce.php
> array_reduce fix return override

- Core/Core.php
Refs https://youtrack.jetbrains.com/issue/WI-50517
I don't like this `<p>` stuff in the docblock lines - maybe the can be removed in follow up PRs.
But since they close with `</p>` already, they should also correctly open (so I added those, too).
> Fix false for return.

- curl/curl.php
Fix optional parameters in `CURLFile::__construct` and `curl_file_create`
https://github.com/php/php-src/blob/94938934127c43b02b23c95de99e4a08aa194122/ext/curl/curl_file.c#L36-L41
https://github.com/php/php-src/blob/86675dd3f90f1b807aacba1a5e6fe5e39f15da32/ext/curl/interface.c#L2660-L2667
> curl_file_create optional parameters

- dom/dom_c.php
The return description of `saveXML` explains that false can be returned if an error occured, but the actual return type did not yet include false.
> Add false return type to saveXML

- apcu/apcu.php
The php manual has an extra $ttl parameter for apcu_inc() and apcu_dec() which is missing in the phpStorm stubs
https://www.php.net/manual/en/function.apcu-inc.php
https://www.php.net/manual/en/function.apcu-dec.php
> add ttl to apcu_inc() / apcu_dec()

- Core/Core.php
stated that since php7 array is valid value for a function, and that case insensitive parameter is deprecated since 7.3
> Update define function documentation

- SPL/SPL_c1.php
SPL_c1.php: SplPriorityQueue add __construct method.
Without it https://github.com/vimeo/psalm fails with an error:
```
PHP Fatal error:  Uncaught UnexpectedValueException: Cannot get method params for SplPriorityQueue::__construct in ./vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php:416
```
---
also fix one tab
> SPL_c1.php: SplPriorityQueue add __construct method.

- PhpStormStubsMap.php
- decimal/decimal.php
Stubs for the decimal  extension (https://php-decimal.io).
I started using this extension but there was no stub for it.
The PR is about version 1.3.0 of the extension.
> Stubs for ext-decimal 1.3.0

- Phar/Phar.php
Correct `\Phar::compress()`, `\Phar::decompress()`, `\PharData::compress()` and `\PharData::decompress()` return data type.
Fix https://youtrack.jetbrains.com/issue/WI-50953
> Correct \Phar::decompress() return data type

- readline/readline.php
Using phpstan I got prompted that the return value of `readline()` might be false.
According to the official docs this holds true. So the stub here is not totally correct. (Even the docs are not 100% correct it seems).
https://www.php.net/manual/en/function.readline.php#refsect1-function.readline-returnvalues
Also in the source: https://github.com/php/php-src/blob/27e83d0fb87c04b61441fb77e963dd4e14ad187e/ext/readline/readline.stub.php#L3
> Fix possible return values from `readline`

- standard/standard_3.php
I doubt if it can be specified as `string[]|false[]|false`? I'm not sure.
> Fix getopt() return type

- redis/Redis.php
**WARNING** This PR is wrong but:
1. your issues are not open
2. I don't know how to fix that.
The current spec does not validate you own example.
The [PECL allows use to write](https://github.com/phpredis/phpredis#zadd):
```
$redis->zAdd('key', 1, 'val1');
```
But the current stub doesn't.
---
I'm sorry, I'm not able to go further. Please let me know what I can do
> Try to fix Redis::zadd

- standard/standard_5.php
According to [the doc](https://www.php.net/manual/en/function.fopen.php), `$use_include_path` is `false` by default.
> Fix default value

- Core/Core.php
Added missing documeation for gc_status core function
https://youtrack.jetbrains.com/issue/WI-52193
> WI-52193 Missing 'gc_status' return type

- soap/soap.php
Hi, the stubs are missing [SoapHeader::__construct](https://www.php.net/manual/en/soapheader.construct.php) so I added it. Thanks.
> Added SoapHeader::__construct()

- standard/password.php
The function also returns `null` if you pass `null` for `$options` instead of `[]`
>  Default value seems to be wrong

- standard/standard_4.php
According official docs first parameter has string type and `options` parameter can't be null.
https://www.php.net/manual/en/function.unserialize.php
https://github.com/php/php-src/blob/beff93f60ddb330cc5b04d716af3ba9cba108c8e/ext/standard/basic_functions.stub.php#L1528
> Change PHPDoc for unserialize

- standard/standard_0.php
Seems like the upstream version is not saved with trim-spaces-at-line-end... which is one of my fave features of phpstorm :-)
> WI-31328 fix definition of image_type_to_extension

- FFI/FFI.php
Fixes/Improvements:
- `FFI::load` allows only string arguments
- `FFI::cdef` returns an instance of FFI in cases where declarations are more than one.
- Although it is noted in the documentation that some FFI functions/mettods passes objects by reference (that is, they can change them), but in reality this is not so. Fix it.
> FFI Improvements

- FFI/FFI.php
Fixes the leftovers from https://github.com/JetBrains/phpstorm-stubs/pull/777#discussion_r410971024
> fix wrong @return at \FFI::cdef()

- standard/standard_9.php
Rationale.
Currently the description of `array_reduce(array $input, $function, $initial = null)` does NOT provide signature for its second argument that is a callback.
This makes people who invoke documentation tooltip actually fail to find this important information and proceed all way back to the php.net manual.
Solution: let's embed the signature of the callback into the description of the `array_reduce()`.
https://youtrack.jetbrains.com/issue/WI-52816
> Add callback signature and example use for the array_reduce

- standard/standard_3.php
According to https://www.php.net/manual/en/function.round.php `round()` can return only float
https://youtrack.jetbrains.com/issue/WI-53376
> Fix round() return value

- curl/curl_d.php
The option CURLOPT_SSL_VERIFYPEER is available since at least PHP 5.
The comment in the documentation is referring about cURL package for the default value.
https://www.php.net/manual/en/function.curl-setopt.php
> Fix invalid tag for CURLOPT_SSL_VERIFYPEER in curl_d.php

- zip/zip.php
list generated using
```php
<?php
echo '<pre>';
$refl = new ReflectionClass(ZipArchive::class);
$const = $refl->getConstants();
foreach($const as $name => $val) {
if (strpos($name, 'OPSYS') === 0) {
echo "
/**
* @link https://www.php.net/manual/en/zip.constants.php#ziparchive.constants.opsys.default
* @since 5.6
*/
const ". $name . " = ". $val. ";
";
}
}
```
> Added ZipArchive::OPSYS_* constants

- zip/zip.php
not sure what the correct value for such a version-dependent constant would be, but for static analysis or autocompletion purposes having it defined at all is usefull in itself.
> Added `ZipArchive::LIBZIP_VERSION`

- dom/dom_c.php
This PR changes an inconsistency in the stubs for the `dom` extension.
The signature for `DOMDocument::saveHTML($node = NULL)` has the uppercase `null` as default value for its first and only `$node` argument.
The PR changes this to the lowercase `null` instead.
At the very least, this will make the file more consistent. However, I suspect that this is the cause for the PHPStan issue at https://github.com/phpstan/phpstan/issues/3478, so this will also hopefully fix that issue.
> Change uppercase NULL into lowercase null for saveHTML default value

- dom/dom_c.php
As a follow-up to the feedback in https://github.com/JetBrains/phpstorm-stubs/pull/840#issuecomment-644787004 I did a quick scan over the return types and adapted those that seemed wrong.
> Adapt return types for DOM extension

- standard/standard_2.php
According to the PHP documentation. The additional parameters for `http_build_query` are defined as:
```
http_build_query ( mixed $query_data [, string $numeric_prefix [, string $arg_separator [, int $enc_type = PHP_QUERY_RFC1738 ]]] ) : string
```
We recently found out that these parameters are not nullable when strict_types enabled. This PR fixes the error below:
```
Exception 'TypeError' with message 'http_build_query() expects parameter 2 to be string, null given'
```
The second parameter is set to `arg_separator.output`. According to the default PHP.ini. That value is in almost any case `&`: arg_separator.output	"&"	PHP_INI_ALL
> Fix for http_build_query

- bz2/bz2.php
- dba/dba.php
- fileinfo/fileinfo.php
- shmop/shmop.php
Correct return value for [`bzopen()`](https://www.php.net/manual/en/function.bzopen.php#refsect1-function.bzopen-returnvalues), [`dba_open()`](https://www.php.net/manual/en/function.dba-open.php#refsect1-function.dba-open-returnvalues), [`finfo_open()`](https://www.php.net/manual/en/function.finfo-open.php#refsect1-function.finfo-open-returnvalues) and [`shmop_open()`](https://www.php.net/manual/en/function.shmop-open.php#refsect1-function.shmop-open-returnvalues) functions.
Return type declared as `resource`, but `false` returned on failure.
> Correct return value for bzopen(), dba_open(), finfo_open() and shmop_open() functions

- cubrid/cubrid.php
- enchant/enchant.php
- fann/fann.php
- interbase/interbase.php
- ldap/ldap.php
- mssql/mssql.php
- mysql/mysql.php
- odbc/odbc.php
- sockets/sockets.php
- ssh2/ssh2.php
- standard/standard_6.php
- sybase/sybase_ct.php
- xml/xml.php
- zip/zip.php
- zlib/zlib.php
Simular of #853
Correct return value for functions:
* [`cubrid_connect()`](https://www.php.net/manual/en/function.cubrid-connect.php#refsect1-function.cubrid-connect-returnvalues)
* [`cubrid_connect_with_url()`](https://www.php.net/manual/en/function.cubrid-connect-with-url.php#refsect1-function.cubrid-connect-with-url-returnvalues)
* [`cubrid_pconnect()`](https://www.php.net/manual/en/function.cubrid-pconnect.php#refsect1-function.cubrid-pconnect-returnvalues)
* [`cubrid_pconnect_with_url()`](https://www.php.net/manual/en/function.cubrid-pconnect-with-url.php#refsect1-function.cubrid-pconnect-with-url-returnvalues)
* [`cubrid_query()`](https://www.php.net/manual/en/function.cubrid-query.php#refsect1-function.cubrid-query-returnvalues)
* …
> Correct return value for PHP internal functions on failure

- ds/ds.php
A constructor for Vector and PriorityQueue's push method had been missing. Thanks and shoutout to the PHPSTAN project, @enumag, @jkuchar and @ondrejmirtes for their patience.
> Data Structures: 3rd Amendment

- redis/Redis.php
See first example in [examples](https://github.com/phpredis/phpredis#example-8) of [PING](https://github.com/phpredis/phpredis#ping) section.
```
/* When called without an argument, PING returns `TRUE` */
$redis->ping();
```
> Parameter $message is optional.

- Dockerfile
- intl/intl.php
- mysqli/mysqli.php
- tests/Model/PHPDocElement.php
- tests/Model/PHPFunction.php
- tests/Model/PHPMethod.php
- tests/Model/PHPParameter.php
- tests/Model/StubProblemType.php
- tests/Model/StubsContainer.php
- tests/Parsers/StubParser.php
- tests/StubsTest.php
- tests/TestData/Providers/StubsTestDataProviders.php
- tests/TestData/mutedProblems.json
- zip/zip.php
This PR adds test that checks that methods that has `@since` version < 7 don't have parameters with scalar type hints and return type hints. 
Why was it done?
If public method in stubs has `@since` version < 7 and at the same time has scalar type hints or return typehint, then overriden by user (that use php 5.6) method will show error that method signature should be compatible with basic one (if one will remove typehints) or error that typehints are not supported. In any case such errors will be false positive and noisy.
Note that I've increased memory_limit. It was required due to all stubs are loaded to the memory by data providers and as far as new tests use data providers more data should be loaded into the memory. Current usage of memory is 132.00 MB
> add tests that scalar type hints/return typehints used with correct since version

- standard/standard_4.php
Second parameter can only be an array, the true/false/array values allowed are on an option inside the array
https://www.php.net/manual/en/function.unserialize.php
> Clarify unserialize() spec

- Reflection/ReflectionProperty.php
This was overlooked in #698 and causes some issues for static analysis,
see https://github.com/doctrine/persistence/pull/122
> Document argument as nullable

- dba/dba.php
These are variadic functions in php 7 and 8
https://wiki.php.net/rfc/named_params will make parameter names of
internal functions part of the API, so having placeholder names instead
of matching names for methods/functions is something that
should probably be changed in many, many places.
(e.g. standard/standard_9.php)
Related to https://youtrack.jetbrains.com/issue/WI-54703 - this process of supporting named arguments should probably be automated in a script that renames parameters in signatures and doc comments
> Fix incorrect parameter name signatures for dba_open and dba_popen

- bcmath/bcmath.php
`@since` should be reserved for the case when the function has been *added* in a given version, not modified.
Because of this, PHPStorm considers `bcmod()` to be available since PHP 7.2, when it was actually available before then:
> Wrong usage of @ since

- intl/intl.php
The argument of IntlBreakIterator::createCharacterInstance is optional. See https://www.php.net/manual/en/intlbreakiterator.createcharacterinstance.php and https://github.com/php/php-src/blob/f78a09101496d05b4fb50fe37b7dbf5d038452ec/ext/intl/breakiterator/breakiterator_arginfo.h#L5
> IntlBreakIterator::createCharacterInstance - optional argument

- intl/intl.php
The argument of IntlBreakIterator::next is optional - see https://www.php.net/manual/en/intlbreakiterator.next.php and https://github.com/php/php-src/blob/f78a09101496d05b4fb50fe37b7dbf5d038452ec/ext/intl/breakiterator/breakiterator_arginfo.h#L48
> IntlBreakIterator::next - optional argument

- intl/intl.php
The argument of IntlBreakIterator::getPartsIterator is optional. See https://www.php.net/manual/en/intlbreakiterator.getpartsiterator.php
> IntlBreakIterator::getPartsIterator - argument is optional

- intl/intl.php
See https://www.php.net/manual/de/function.idn-to-ascii.php and https://github.com/php/php-src/blob/046cc5e4c213b836546689d5bdc8925f057c24b5/ext/intl/php_intl.stub.php#L274
> Fourth argument of idn_to_ascii() is optional

- apcu/apcu.php
This is not documented in php.net for some reason but it returns the same array as ApcuIterator entries.
> [apcu] apcu_key_info($key) should return array|null

- Reflection/ReflectionProperty.php
In PHP 8, `ReflectionProperty::getType()` returns either a `ReflectionNamedType` or a `ReflectionUnionType`:
https://3v4l.org/3X0Rp
So the correct return value is `ReflectionType`, just like [ReflectionParameter::getType()](https://github.com/JetBrains/phpstorm-stubs/blob/874def36f96dbb7db2eb2ff5e47ff54ac3ea34fc/Reflection/ReflectionParameter.php#L129-L139).
> ReflectionProperty::getType() returns ReflectionType

- .travis.yml
- tests/Model/BasePHPElement.php
- tests/Model/PHPClass.php
- tests/Model/PHPConst.php
- tests/Model/PHPDefineConstant.php
- tests/Model/PHPFunction.php
- tests/Model/PHPInterface.php
- tests/Model/PHPMethod.php
- tests/Model/PHPParameter.php
- tests/Model/PHPProperty.php
- tests/Model/StubsContainer.php
- tests/Model/Tags/RemovedTag.php
- tests/Parsers/ExpectedFunctionArgumentsInfo.php
- tests/Parsers/MetaExpectedArgumentsCollector.php
- tests/Parsers/StubParser.php
- tests/Parsers/Utils.php
- tests/Parsers/Visitors/ASTVisitor.php
- tests/Parsers/Visitors/MetaOverrideFunctionsParser.php
- tests/Parsers/Visitors/ParentConnector.php
- tests/StubsMetaExpectedArgumentsTest.php
Tests are updated to use features of php 8. Note that `composer cs` fails due to union types that are currently not supported by cs fixer are used. That's why build is failing but all other checks pass
> Migrate tests to php 8

- soap/soap.php
Some of them were removed here, so I returned them: https://github.com/JetBrains/phpstorm-stubs/commit/f23297fad60d3db5ea951e06d06ba4f568d75cb3#diff-642148d22d9633b96b4f1007d0831e7eea0148d7fd4fe1ad18bb6086bfd5e2cbR463-R731
I also added `@removed 8.0` to them.
First discovered here: https://github.com/phpstan/phpstan/issues/3975
> Soap - returned old-style constructors

- bcmath/bcmath.php
bcscale() sets scaling globally, it is not pure.
> Make bcscale unpure

- PhpStormStubsMap.php
- newrelic/newrelic.php
Most of the definition was added in #411, but the second commit removed the actual function definition
> Properly add newrelic_record_datastore_segment to newrelic

- SimpleXML/SimpleXML.php
If SimpleXMLElement is extended, it's children are also instances of the extending class.
> Set correct return type for SimpleXMLElement::__get()

- date/date_c.php
This means that the constants do not exist on DateTimeImmutable in PHP 7.1 for example.
> Class constants were moved from DateTime to DateTimeInterface in PHP 7.2

- SimpleXML/SimpleXML.php
When the $filename is passed, it saves XML to disk. See https://github.com/phpstan/phpstan/issues/4113#issuecomment-732128847 for details. Thank you.
> SimpleXMLElement::asXML() is not pure

- imagick/imagick.php
`$normalized` is an int:
https://www.php.net/manual/en/imagickpixel.getcolor.php
```php
ImagickPixel::getColor ([ int $normalized = 0 ] ) : array
```
> Fix ImagickPixel::getColor() default value

- Ev/Ev.php
Method `io` returns `EvIo` instead `void` type
> Fix return type for EvLoop->io

- tests/StubsTest.php
- tests/StubsTypeHintsTest.php
- Using the `assertCount` to assert expected is same as result count.
- Using the `assertStringNotContainsString` to assert expected string is not contains specific string.
> Improve assertions

- mongodb/mongodb.php
Added missing MongoDB\Driver\Cursor methods - current(), key(), next(), rewind() and valid() - to comply with the [current class synopsis](https://www.php.net/manual/en/class.mongodb-driver-cursor.php).
> Add MongoDB Cursor methods

- bcmath/bcmath.php
- composer.json
- tests/Model/BasePHPElement.php
- tests/Model/PHPClass.php
- tests/Model/PHPConst.php
- tests/Model/PHPDefineConstant.php
- tests/Model/PHPFunction.php
- tests/Model/PHPInterface.php
- tests/Model/PHPMethod.php
- tests/Model/PHPParameter.php
- tests/Model/PHPProperty.php
- tests/Model/PhpVersions.php
- tests/Parsers/Utils.php
- tests/StubsTest.php
Find duplicated functions based on versions intersection like
```
#[PhpStormStubsElementAvailable(from: '7.1', to: '7.4')]
function bcmod (string $num1, string $num2, ?int $scale = 0)
{}
#[PhpStormStubsElementAvailable(from: '7.2', to: '8.0')]
function bcmod (string $num1, string $num2, ?int $scale = 0)
{}
```
> use versions range to search for duplicated functions

- SimpleXML/SimpleXML.php
See https://www.php.net/manual/en/simplexmlelement.construct.php
Example: new SimpleXmlElement('foo')
> Add throws tag to SimpleXMLElement::__construct()

- Core/Core.php
- mysqli/mysqli.php
- standard/standard_0.php
- standard/standard_4.php
- standard/standard_5.php
- tests/Model/BasePHPElement.php
- tests/Model/PHPClass.php
- tests/Model/PHPConst.php
- tests/Model/PHPFunction.php
- tests/Model/PHPInterface.php
- tests/Model/PHPMethod.php
- tests/Model/PHPParameter.php
- tests/Model/PHPProperty.php
- tests/Model/StubProblemType.php
- tests/Parsers/Utils.php
- tests/StubsPhpDocTest.php
- tests/StubsTest.php
- tests/StubsTypeHintsTest.php
- tests/TestData/Providers/Stubs/StubMethodsProvider.php
- tests/TestData/mutedProblems.json
- xdebug/xdebug.php
Typehints are not being stored in arrays instead of a single string. Related tests are updated to use arrays.
> Typehint mismatch in signature and phpdoc

- Reflection/ReflectionType.php
There's no `getName()` method in the `ReflectionType` abstract class, this is really misleading. It is only available in one of the subclasses, in the `ReflectionNamedType`. `ReflectionUnionType`, on the contrary, does not have this method.
Also there's no clear replacement. In case of `ReflectionUnionType` developer has to iterate over `$union->getTypes()` recursively.
See https://www.php.net/manual/ru/class.reflectiontype.php
> Fixed ReflectionType::__toString()

- tests/StubsMetaExpectedArgumentsTest.php
- tests/StubsMetaInternalTagTest.php
- tests/StubsParameterNamesTest.php
- tests/StubsPhpDocTest.php
- tests/StubsTest.php
- tests/StubsTypeHintsTest.php
As thrown exceptions are suppressed by dataproviders
> prepare stubs in setup method

- xsl/xsl.php
`transformToXml` can return null. (See [documentation](https://www.php.net/manual/en/xsltprocessor.transformtoxml.php))
This example should return null.
```php
$stylesheet = new \DOMDocument();
$stylesheet->loadXML('<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"></xsl:stylesheet>');
$processor = new \XSLTProcessor();
$document = new \DOMDocument();
$document->loadXML('<root></root>');
$processor->importStylesheet($stylesheet);
$result = $processor->transformToXml($document);
```
I have fixed the type hint in this PR.
> Add missing type hint to XSL transformToXml

- tests/Model/BasePHPElement.php
- tests/Model/PHPFunction.php
- tests/Model/PHPMethod.php
- tests/Model/PHPParameter.php
- tests/StubsTest.php
- tests/StubsTypeHintsTest.php
Store types from LanguageLevelTypeAware attribute to separate array and update tests accordingly. Compare typehints from reflection with signature and if it doesn't match try to find the same typehints in attribute
> store types from attribute to separate array

- mysqli/mysqli.php
The annotation reflects the return type in a human-readable format but not in machine-readable.
> mysqli_result::fetch_fields() can return false

- meta/.phpstorm.meta.php
Covering the support for dynamically-prefixed table names in SQL injections ([WI-16205](https://youtrack.jetbrains.com/issue/WI-16205)).
> Provided 'sql_injection_subst' stub & description; updated the 'map' description

- generate-stub-map
classes have the same FQNs but stub currently has "FQN => path" key-value
> skip couchbase_v2 during stub map generation

- pq/pq.php
Stub for pq was missing `resource` types in two `@var` tags
@see https://github.com/m6w6/ext-pq/issues/39
> add missing type name in var tag for pq

- standard/standard_6.php
This function depends on side-effects, as can be demonstrated with this minimal test case:
```php
var_dump(realpath('foo')); // bool(false)
mkdir('foo');
var_dump(realpath('foo')); // string(8) "/tmp/dir"
```
https://youtrack.jetbrains.com/issue/WI-59567
> Remove Pure attribute on realpath

- Ev/Ev.php
- curl/curl_d.php
- gnupg/gnupg.php
- intl/IntlChar.php
- libvirt-php/libvirt-php.php
- mongo/mongo.php
- oci8/oci8.php
- pdflib/PDFlib.php
- rdkafka/RdKafka/ProducerTopic.php
- redis/Redis.php
- wincache/wincache.php
- yaf/yaf.php
I used the tool I maintain ([Doctum](https://github.com/code-lts/doctum#readme)) to find the errors.
Here is the online version of the generated API docs: https://doctum.long-term.support/api-docs/phpstorm-stubs/
<details><summary>Full error list (38) before fixes (most errors are not fixed)</summary>
<p>
```
ERROR: The "reschedule_cb" parameter of the method "set" is missing a @param tag on "EvPeriodic::set" in Ev/Ev.php:857
ERROR: The "loop" parameter of the method "__construct" is missing a @param tag on "EvFork::__construct" in Ev/Ev.php:1212
ERROR: The "loop" parameter of the method "createStopped" is missing a @param tag on "EvFork::createStopped" in Ev/Ev.php:1223
ERROR: The "reschedule_cb" parameter of the method "periodic" is missing a @param tag on "EvLoop::periodic" in …
```
> phpdoc blocks fixes

- standard/standard_3.php
For tools which read the phpdoc, `@throws` tag should be use.
> Fix intdiv throws annotation

- date/date_c.php
DateTimeImmutable::modify can return false on modification failure, update the docblock to reflect this.
> DateTimeImmutable::modify can return false

- hash/hash.php
hash_{update,update_stream,update_file,final} accept HashContext instead of resource since PHP 7.2 instead of 8.0.
> Wrong LanguageLevelTypeAware of some hash functions

- gd/gd.php
For PHP8 and named arguments, the true name of the parameters/arguments is important.
updated the functions with argument `fontfile` to `font_filename`. 
Verified using function reflection.
> renamed param fontfile to font_filename

- session/session.php
I got an error when using named arguments. (PHPStan and Psalm were working correctly)
ref: https://www.php.net/manual/en/function.session-set-save-handler.php
> session_set_save_handler(object $sessionhandler, bool $register_shutdown = true): bool
> fixed wrong arg name for session_set_save_handler

- ds/ds.php
The stubs are declared according to PHP [documentation](https://www.php.net/manual/en/ds-set.construct.php). However the documentation is bugged.
See my reports:
https://bugs.php.net/bug.php?id=81157
https://github.com/php-ds/ext-ds/issues/167
> Fix \Ds\Set::__construct()

- ibm_db2/ibm_db2.php
See the [source code](https://github.com/php/pecl-database-ibm_db2/blob/19850ece1954bb24f433ea2286f447a7b6c85da0/ibm_db2.c#L7457-L7462):
```c
/* Returning last insert ID (if any), or otherwise NULL */
if (last_id[0] != '\0') {
ZEND_RETURN_STRING(last_id, 0);
} else {
RETURN_NULL();
}
```
> db2_last_insert_id may return NULL

- Core/Core.php
- PDO/PDO.php
- Phar/Phar.php
- curl/curl.php
- date/date.php
- date/date_c.php
- imagick/imagick.php
- session/session.php
- standard/standard_2.php
- standard/standard_3.php
- standard/standard_4.php
- standard/standard_6.php
While the package requires PHP 8 for development,
https://github.com/JetBrains/phpstorm-stubs/blob/a09a014a1984d2ac875c6b1220b7f17ca7d0a873/composer.json#L16-L17
It doesn't require PHP 8 when the package is used as a library.
Although, some code in the package is currently not compatible with PHP 7:
https://github.com/JetBrains/phpstorm-stubs/blob/a09a014a1984d2ac875c6b1220b7f17ca7d0a873/PDO/PDO.php#L1166-L1170
An attempt to use this code with PHP 7 causes a parse error:
```
php -l PDO/PDO.php
Parse error: syntax error, unexpected '0' (T_LNUMBER), expecting function (T_FUNCTION) or const (T_CONST) in PDO/PDO.php on line 1167
```
> Avoid using multi-line annotations for PHP 7 compatibility

- date/date_c.php
Some methods can return `false` - this was not properly documented in the stub.
See related ticket: https://youtrack.jetbrains.com/issue/WI-61262
> Synchronized method return values with the official docs.

- standard/standard_2.php
- standard/standard_9.php
Functions are actually Pure in terms of PhpStorm (don't have side effects) but result of function calls is different. For such cases Pure attribute has parameter $mayDependOnGlobalScope that indicates whether the function result may be dependent on anything except passed variables
> mark rand_* functions as $mayDependOnGlobalScope

- redis/Redis.php
- redis/RedisCluster.php
When `declare(strict_types=1);` is set you cant pass a float to zRemRangeByScore without triggering a type error. So I think it's better to document this as such.
> Use strict typing for Redis zRemRangeByScore

- ssh2/ssh2.php
Hi :raised_hand:
PHP Documentation: https://www.php.net/manual/ru/function.ssh2-connect.php
On the official php page, this function has a default value of "22" for the "port" parameter
> ssh2_connect :: default port 22

- imap/imap.php
> WI-62183 Stubs for imap_delete and imap_undelete have wrong type for $message_num in PhpDoc

- standard/standard_6.php
The actual issue reported in WI-59165 was already fixed.
However the type of the $associative parameter has only changed since PHP 8.0 to bool from int.
I have added the #[LanguageLevelTypeAware] attribute accordingly.
I have not touched the default value and PhpDoc, which would still be wrong for PHP 7.4. But there doesn't seem to be a way to also fix those.
> WI-59165 Invalid stub for get_headers function: The associative parameter has been changed from int to bool in PHP 8.0

- SPL/SPL_c1.php
As pointed out in the PHP manual docs, some methods may return `false` or `null` upon failure.
> Update `SplFileInfo` return types to include `false`/`null` on failure values

- Reflection/Reflector.php
> Reflector::export has been removed in 7.4

- pcre/pcre.php
`preg_last_error` and `preg_last_error_msg` are functions that definitionally read state external to them and are impure.
Their return values are completely impure and defined by the hidden state of other preg functions.
> preg_last_error / preg_last_error_msg are not pure

- pcre/pcre.php
This reverts commit 357a8a0b37bcba30c102d24a3b5ab95c70588f0f.
Caused by incorrect understanding of how #[Pure] works. https://youtrack.jetbrains.com/issue/WI-56211
> Revert "Update pcre.php"

- grpc/grpc.php
This PR contains two fixes.
1.  https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/channel_credentials.c#L157
```c
char *pem_root_certs = NULL;
grpc_ssl_pem_key_cert_pair pem_key_cert_pair;
php_grpc_int root_certs_length = 0;
php_grpc_int private_key_length = 0;
php_grpc_int cert_chain_length = 0;
pem_key_cert_pair.private_key = pem_key_cert_pair.cert_chain = NULL;
```
In PhpDoc the default value is the empty string, but in the actual C code the default value is null
2. https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/channel_credentials.c#L161
```
/* "|s!s!s!" == 3 optional nullable strings */
if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "|s!s!s!",
```
`|s!s!s!` In `zend_parse_parameters` used in the method indicates that "all are optional and nullable", and the …
> Fix parameter definition for Grpc\ChannelCredentials::createSsl

- composer.json
The changes were tested locally on PHP 8.1 beta.
This is to support PHP CS Fixer runs for https://github.com/JetBrains/phpstorm-stubs/pull/1205
> Change php-cs-fixer to "dev-master" instead of "@stable" to parse 8.1 readonly properties

- standard/standard_1.php
- standard/standard_2.php
- standard/standard_4.php
- standard/standard_5.php
- standard/standard_6.php
- standard/standard_7.php
- standard/standard_9.php
Adds the 'Pure' attribute to filesystem functions where it was missing. Also sets the `$mayDependOnGlobalScope` flag where appropriate.
> Add pure attribute to filesystem functions

- gmp/gmp.php
- standard/standard_1.php
- standard/standard_2.php
- standard/standard_9.php
mt_rand both reads and modifies global RNG state internally.  random_int()/random_bytes() would modify OS-level state. gmp_random_* modify random state in GMP. array_rand, shuffle, str_shuffle are the same. They all effectively call mt_rand() internally and change state
> [phpstorm-stubs] remove Pure attribute on rand functions that can change global state

- standard/standard_4.php
mixed already contains false. Removing should improve inspections behavior a bit
> [phpstorm-stubs] WI-63732 remove false from return type

- Core/Core_c.php
- SPL/SPL_c1.php
- standard/_types.php
This is a rebase of #1212, with some additional improvements.
Still, even with these stubs, class-based iterator types (`\Traversable` and all subtypes, including `\Iterator`) are still broken: [WI-62323 (comment)](https://youtrack.jetbrains.com/issue/WI-62323#focus=Comments-27-5243614.0-0)
I added an additional `@template-implements iterable<TKey, TValue>` in the base `\Traversable` class, hoping that would at least simplify the implementation of a fix inside of phpstorm, by allowing the `\Traversable` type not only to extend from `iterable`, but also the passing of template parameters&inheriting iteration behavior from `iterable`.
> Iterator, SPL, and Fiber templates (rebased from #1212, improved)

- Reflection/ReflectionAttribute.php
- Reflection/ReflectionClass.php
- Reflection/ReflectionClassConstant.php
- Reflection/ReflectionFunctionAbstract.php
- Reflection/ReflectionParameter.php
- Reflection/ReflectionProperty.php
Hopefully this PR is the correct direction for attribute class types to be inferred by PhpStorm.
```php
$attributes = $reflectionObject->getAttributes(MyAttribute::class);
foreach ($attributes as $attribute) {
// With @template annotations, hopefully PhpStorm can infer the type of $object as `MyAttribute`.
$object = $attribute->newInstance();
}
```
> Template ReflectionAttribute

- Core/Core_c.php
- tests/TestData/mutedProblems.json
This reverts commit ec24a9ac53b5b4cc258dd457aab42781e7763df1.
Closure object can be called with parameters despite reflection doesn't return any parameter
```
<?php
function testClosure(Closure $cb, $param) { var_dump($cb($param));}
testClosure($cb = fn($param) => $param,1);
```
> Revert "Closure::__invoke() does not have any parameters in PHP"

- pcre/pcre.php
The secont parameter has default `null` value:
https://www.php.net/preg_quote
> Fix `preg_quote` signature

- redis/RedisCluster.php
- The multi() method should return a RedisCluster instance, not a Redis one
- Fixed a similar issue for a thrown exception class name
- added the `redis.clusters.auth` line
Those changes are from https://github.com/zgb7mtr/phpredis_cluster_phpdoc/blob/master/src/RedisCluster.php , which is the base file that was used for this stub.
> Fix some type hinting errors in the RedisCluster stub

- Core/Core.php
- standard/basic.php
- standard/standard_0.php
- standard/standard_1.php
- standard/standard_2.php
- standard/standard_3.php
- standard/standard_4.php
- standard/standard_6.php
- standard/standard_7.php
- standard/standard_9.php
Adds the `$mayDependOnGlobalScope` to functions which depend on external state. There are a multitude of reasons for this:
* Uses the system clock
* Reads system configuration
* Influenced by PHP ini settings
* Locale dependant
* Reads from the filesystem
* Based on PHP symbols/variable scope
Initially this started out as just adding the flag to `hrtime()` but I noticed so many other cass in the same file I went through everything marked pure in the `standard/` and `Core/` directories.
> Flag functions that are marked pure that depend on external state

- Core/Core_c.php
The `interface Stringable` stub definition doesn't match the contents published on php.net:
* https://www.php.net/manual/en/class.stringable.php
* https://www.php.net/manual/en/language.oop5.magic.php#object.tostring
* https://wiki.php.net/rfc/stringable
The stub mentions the term _serializable_, which is not even mentioned in the links provided.
> Fix stringable interface

- memcached/memcached.php
Related to https://github.com/phpstan/phpstan/issues/6263
According to [PHP documentation](https://www.php.net/manual/en/memcached.constants.php), the `Memcached::HAVE_**` constants are booleans. The stub here is correct as to the PHPDoc only, correctly typing them as booleans. However, the values themselves are integers of `1` and `0`. I think this was set as such because in the C source code, the values used are `1` and `0` but the registering function is `REGISTER_MEMC_CLASS_CONST_BOOL`.
https://github.com/php-memcached-dev/php-memcached/blob/d7daff649406efbd43af3253212b1cb946ff3f85/php_memcached.c#L4362-L4366
However, checking with `var_dump`, these constants are actually booleans.
https://github.com/paulbalandan/phpstan-bug6263/runs/5032025575?check_suite_focus=true
> Update values of `Memcached::HAVE_**` constants

- .gitignore
- runTests.sh
There are 3 main changes:
- the run tests script was calling the dumper incorrectly, causing a php error and missing json dump
- the dumped file should have been gitignored
- since it takes some time to build the docker images, I opted for showing the output
I don't have a strong opinion on these changes, but I thought they would be useful.
> Generate dump correctly, gitignore it, display docker build output

- redis/Redis.php
Retry and backoff options described https://github.com/phpredis/phpredis/#retry-and-backoff
The underscore param name version from https://github.com/phpredis/phpredis/#connect-open
Verified using PHP itself running PHPRedis 5.3.6:
```php
>>> Redis::OPT_MAX_RETRIES
=> 11
>>> Redis::OPT_BACKOFF_ALGORITHM
=> 12
>>> Redis::OPT_BACKOFF_BASE
=> 13
>>> Redis::OPT_BACKOFF_CAP
=> 14
>>> Redis::BACKOFF_ALGORITHM_DEFAULT
=> 0
>>> Redis::BACKOFF_ALGORITHM_DECORRELATED_JITTER
=> 1
>>> Redis::BACKOFF_ALGORITHM_FULL_JITTER
=> 2
>>> Redis::BACKOFF_ALGORITHM_EQUAL_JITTER
=> 3
>>> Redis::BACKOFF_ALGORITHM_EXPONENTIAL
=> 4
>>> Redis::BACKOFF_ALGORITHM_UNIFORM
=> 5
>>> Redis::BACKOFF_ALGORITHM_CONSTANT
=> 6
>>> new ReflectionMethod(Redis::class, 'connect')
=> ReflectionMethod {#2655
+name: "connect", …
```
> Adding Redis retry & backoff constants and params

- dom/dom_c.php
Due to false positive errors from PHPStan I found out that the stubs from this repo have incorrect types for `DOMNode` & `DOMElement` properties. All of these are actually correctly noted in the docs: [DOMNode](https://www.php.net/manual/en/class.domnode.php), [DOMElement](https://www.php.net/manual/en/class.domelement.php) and I have also verified all of these in runtime:
* `DomNode::$nodeValue` - example: https://3v4l.org/qa86V
* `DomNode::$localName` - example: https://3v4l.org/5613l
* `DomElement::$parentNode` - example: https://3v4l.org/Dv8CN
* `DomElement::$firstChild` - example: https://3v4l.org/FcLun
* `DomElement::$lastChild` - example: https://3v4l.org/TifIr
* `DomElement::$previousSibling` - example: https://3v4l.org/t3rAL
* `DomElement::$nextSibling` - example: …
> Fix `DOMNode` & `DOMElement` property types

- newrelic/newrelic.php
Documents for newrelic give a fourth signature option for
newrelice_notice_error() which is not listed in the stub.
newrelic_notice_error(string $errstr, Throwable|Exception $e)
See https://docs.newrelic.com/docs/apm/agents/php-agent/php-agent-api/newrelic_notice_error/
> Additional signature for newrelic_notice_error for passing an Exception

- Reflection/ReflectionClass.php
Add template to ReflectionClass to infer type in expression like 
```
$class = new ReflectionClass(MyClass::class);
$instance = $class->newInstanceWithoutConstructor();
```
> [phpstorm-stubs] WI-60009 add template to ReflectionClass

- imap/imap.php
- reverse is boolean as of php 8.0
- search_criteria and charset are now optional
> Update imap_sort documentation

- mongodb/mongodb.php
I don't believe this interface is deprecated. 
I think it was marked by mistake. Maybe confused with one in the core (different namespace), which is deprecated in PHP 8.1
> MongoDB Serializable interface is not deprecated

- redis/Redis.php
I believe this is a typo.
see https://github.com/phpredis/phpredis#mset-msetnx
> fix: Redis::mset should be mSet

- standard/standard_9.php
... according [manual for `assert()`](https://www.php.net/manual/en/function.assert.php#refsect1-function.assert-parameters)
> fix(standard/assert): second parameter can be `Throwable` since 7.0

- ds/ds.php
Discovered in https://github.com/phpstan/phpstan/issues/7258.
`Collection` extends `\IteratorAggregate` in both [the `php-ds/php-ds` polyfill](https://github.com/php-ds/polyfill/blob/master/src/Collection.php) and [the `ext-ds` extension](https://github.com/php-ds/ext-ds/blob/master/src/php/classes/php_collection_ce.c), so the stubs here should match.
Note that `Traversable` is removed from the `extends` because `IteratorAggregate` already extends `Traversable`.
> Fix: `Ds\Collection` should extend `IteratorAggregate`.

- FFI/.phpstorm.meta.php
- FFI/FFI.php
Correction of the name of the CType's constant:
**Before:**
```
FFI\CType::TYPE_LONG_DOUBLE
```
**After:**
```
FFI\CType::TYPE_LONGDOUBLE
```
The problem was found here: https://github.com/symfony/symfony/pull/46773#discussion_r907116975
> Fix FFI\CType::TYPE_LONG_DOUBLE constant typo.

- redis/Redis.php
Fix for `Required parameter '$value' missing` when you calling `config()` method with GET option. E.g. `$redis->config('GET', 'databases')`
> Update Redis config() method

- standard/standard_4.php
- tests/BaseFunctionsTest.php
- tests/TestData/mutedProblems.json
Ideally should be fixed using annotation from WI-61322 but until WI-61322 is fixed let's create a dup as users complain about the wrong signature
> WI-66334 add duplicated signature of var_dump

- standard/standard_8.php
Add missing ExpectedValue "EXTR_IF_EXISTS" to `extract`'s `$flags`
See issue tracker WI-67763
https://youtrack.jetbrains.com/issue/WI-67763/Add-EXTRIFEXISTS-as-to-ExpectedValues-for-extracts-flags-parameter
> Update extract's ExpectedValues

- tests/Model/StubsContainer.php
Added this while tracking down "Attempt to read property "parameters" on null" error.
Happens when \StubTests\Model\BasePHPElement::entitySuitsCurrentPhpVersion returns false when running tests on PHP beta. It is not expected that getenv('PHP_VERSION') would return e.g. PHP8.2_beta:
> Added (!$functions) handling

- gearman/gearman.php
$unique parameter's type should be nullable string https://github.com/php/pecl-networking-gearman/blob/master/gearman.stub.php#L62
> [phpstorm-stubs] WI-67518 Gearman:do*() methods fix

- redis/Redis.php
I compared the current stub file with the original https://github.com/phpredis/phpredis/blob/develop/redis.stub.php and updated phpdocs, added/updated arguments.
There are also many undocumented methods (class below), so I didn't add them
```php
class Redis {
public function _compress(string $value): string {}
public function _pack(mixed $value): string {}
public function _uncompress(string $value): string {}
public function _unpack(string $value): mixed {}
public function acl(string $subcmd, string ...$args): mixed {}
public function command(string $opt = null, string|array $arg): mixed {}
public function copy(string $src, string $dst, array $options = null): bool {}
public function debug(string $key): string {}
public function failover(?array $to = null, bool $abort = false, int …
```
> Update Redis phpdocs, added missing arguments

- Core/Core_c.php
Now, when using `WeakReference`, PhpStorm cannot infer the type returned by the `get()` method, which is inconvenient.
This PR adds template annotations that allow PhpStorm to accurately infer types.
See `WeakReference` in Psalm [stubs](https://github.com/vimeo/psalm/blob/2fdcd5a5fc48ddb585cc6261e40e2460187142eb/stubs/CoreGenericClasses.phpstub)
> Add template annotations for WeakReference

- soap/soap.php
Check this bug for more context: https://github.com/phpstan/phpstan/issues/8111
> fix docblock variable type for SoapFault

- Core/Core_c.php
Since you can never add a contravariant (via a method parameter) these types can be documented as `covariant`
https://phpstan.org/blog/whats-up-with-template-covariant
This would allow:
```
Traversable<Animal> = new Traversable<Cat>();
```
of course this wouldn't work for any sub-types that also use `TValue` as a parameter.
> Add covariance to Iterator and Traversable

- date/date_c.php
Iterated type is DateTime or DateTimeImmutable depending on $start  constructor argument type.
> Make DatePeriod generic

- rdkafka/RdKafka/ConsumerTopic.php
rd-kafka library implements RdKafka\ConsumerTopic::consume() method as do consume till Kafka service return value is not empty. Need to update return type.
> fixed return type RdKafka\ConsumerTopic::consume()

- redis/RedisCluster.php
Even the documentation suggests to use \RedisCluster::BEFORE (or ::AFTER), which are strings (`before`, `after`).
> fix: `$position` parameter to `lInsert()` is string

- date/date_c.php
As documented in https://www.php.net/manual/en/datetimezone.construct.php
> DateTimeZone::__construct throws Exception

- standard/standard_defines.php
I know the constant `STREAM_MUST_SEEK` below the link comment is only written there in the comments of the linked docs page but at least it is a page mentioning it and that is not 404
> Update 404 link for stream constants

- bcmath/bcmath.php
Fixes default value for `$scale` on PHP 8:
- [bcdiv](https://www.php.net/manual/en/function.bcdiv.php):
```php
bcdiv(string $num1, string $num2, ?int $scale = null): string
```
- [bcmod](https://www.php.net/manual/en/function.bcmod.php):
```php
bcmod(string $num1, string $num2, ?int $scale = null): string
```
> Fix bcdiv/bcmod() $scale default value

- memcached/memcached.php
Fixes https://youtrack.jetbrains.com/issue/WI-70049/Document-Memcached-checkKey-method
Memcached exposes a method `checkKey`: https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached.c#L3454
The php-memcached stub file also mentions this method: https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached.stub.php
Can be used like this:
```
$mem = new Memcached();
$checkKey = $mem->checkKey("valid");
var_dump($checkKey);
```
this will output `true`.
But for example a key with a space in it will not pass the validation and return `false`.
> WI-70049 - Documented Memcached checkKey method

- PhpStormStubsMap.php
- amqp/amqp.php
Resolves https://youtrack.jetbrains.com/issue/WI-70026/AMQP-stubs-out-of-date
AMQP stubs have fallen slightly out of date resulting in incorrect types in method signatures. This PR updates those to reflect the latest changes.
> Update amqp stubs according to latest from extension repository

- openssl/openssl.php
According to https://www.php.net/manual/en/function.openssl-random-pseudo-bytes.php this function returns `string` only since PHP 7.4 already. I could also find a changelog entry on
https://www.php.net/ChangeLog-7.php#PHP_7_4
> openssl_random_pseudo_bytes() now throws in error conditions.
I wanted to double-check via php-src, but couldn't find the right place in the 7.4 tag and wasn't a 100% sure. maybe you want to still double-check this somehow if possible
> [phpstorm-stubs] fix openssl_random_pseudo_bytes return type

- Core/Core.php
Fixes: https://youtrack.jetbrains.com/issue/WI-70341/For-function-define-PHP-lib-stubs-marks-caseinsensitive-as-required-for-PHP-5-but-is-actually-option
Mark parameter `$case_insensitive` for function `define` as optional with default value `false`. Also mark it as available for older versions of PHP.
> [phpstorm-stubs] mark $case_insensitive optional for define

- standard/standard_7.php
When I read the documentation https://www.php.net/manual/en/function.rewinddir.php right the return value is void. When I read the phpcode for rewind_dir it return value is void as well. If I read `php_userstreamop_rewinddir` correctly. I read the custom stream wrappers implementation as the original call `PHP_FUNCTION(rewinddir)` looks like just calling a macro `php_stream_rewinddir` without processing the return value. I stumbled upon this as I wrote code using phpstorm IDE hints and phpstan tells me, that there is no return value to pay respect to.
I am not sure whether my findings are correct as I am only reading PHP source code infrequently and I am not sure whether the issue might be in phpstan and the docs.
> Update return type for rewinddir to void

- standard/_types.php
Fix \Generator type template from:
psalm - https://github.com/vimeo/psalm/blob/c6551a61e7a62426c0e9c8f92b33cf09e8346db9/stubs/CoreGenericClasses.phpstub#L21
phpstan - https://github.com/phpstan/phpstan/blob/53a2caa820fb5d603c5d623212e7ce421a09019e/website/src/_posts/generics-in-php-using-phpdocs.md#type-safe-iterators-and-generators
> Generator template covariant yield\return

- Reflection/ReflectionUnionType.php
Since [DNF types](https://wiki.php.net/rfc/dnf_types) have been introduced in PHP 8.2, types returned by `ReflectionUnionType::getTypes()` include `ReflectionIntersectionType` in addition to `ReflectionNamedType`:
https://3v4l.org/ZFKZ6#v8.2.1
I'm not entirely sure of the syntax in this patch, suggestions welcome.
> Allow DNF types in ReflectionUnionType::getTypes()

- standard/standard_4.php
$as_number was always optional, see https://3v4l.org/uK5ro and https://www.php.net/manual/en/function.hrtime.php
> hrtime(): $as_number is optional

- redis/Redis.php
See https://github.com/phpredis/phpredis/blob/develop/redis.stub.php#L2915
It might be better to sync the whole stub. Phpredis devs finally updated it and added the missing docblocks.
> `$iterator` in Redis scan() can be also null

- mailparse/mailparse.php
According to the source, it returns false when called incorrectly, or when the requested part was not found.
> mailparse_msg_get_part() can return false

- ibm_db2/ibm_db2.php
See php/pecl-database-ibm_db2#53.
> [ibm_db2] Argument 1 in `db2_connect()` and `db2_pconnect()` can contain the connection password

- meta/locales/.phpstorm.meta.php
**Steps to reproduce:**
Write:
```php
setlocale(LC_ALL, 'de_DE', '<caret>');
```
**Expected**
Completion at third argument (second locale)
**Actual**
No completion because of this stub definition:
```php
function setlocale(
#[ExpectedValues([LC_ALL,  LC_COLLATE,  LC_CTYPE,  LC_MONETARY,  LC_NUMERIC,  LC_TIME,  LC_MESSAGES])] int $category,
#[PhpStormStubsElementAvailable(from: '8.0')] $locales,
#[PhpStormStubsElementAvailable(from: '5.3', to: '7.4')] $rest,
...$rest
): string|false {}
```
> Fixed meta for setlocale when more than one locale is provided

- standard/standard_0.php
Since PHP 8 it will throw if the constant is undefined. See https://www.php.net/manual/en/function.constant.php
But this is most likely not the best way to add that info. There is no PHP-version specific throws, right?
UPDATE: found https://youtrack.jetbrains.com/issue/WI-72311 afterwards and adapted the return type description too
> Add throws PHPDoc to `constant()`

- mysqli/mysqli.php
https://www.php.net/manual/en/mysqli.get-proto-info.php The stubs were wrong.
> protocol_version was always an int property

- dom/dom_c.php
This was never implemented in PHP, and got removed as a consequence in PHP 8.0. This might be introduced later, but for now the stubs shouldn't contain a method that isn't there.
> Remove compareDocumentPosition

- SPL/SPL_c1.php
According to php.net documentation, SplMinHeap extends SplHeap and inherits the `SplHeap::insert()` method [which always returns true](https://www.php.net/manual/en/splheap.insert.php). Return types for `SplHeap::insert()` and `SplMaxHeap::insert()` are correctly defined, however, the return type of `SplMinHeap::insert()` is `void`.
> Fix return type of SplMinHeap::insert(): void -> true

- PhpStormStubsMap.php
- tests/Tools/generate-stub-map
Currently directory can be obtained with expression
```php
$stubsDir = dirname((new \ReflectionClass(PhpStormStubsMap::class))->getFileName());
```
After this PR it could be simplified to
```php
$stubsDir = PhpStormStubsMap::DIR;
```
> Added PhpStormStubsMap::DIR constant to simplify integration

- Core/Core_c.php
- curl/curl_d.php
- hash/hash.php
- pgsql/pgsql.php
Updated constants, changed return type for WeakMap::getIterator in PHPDoc and added one more parameter to function hash_pbkdf2().
> [phpstorm-stubs] Tried to fix tests that used to fail for PHP 8.1 and PHP 8.2

- gd/gd.php
- odbc/odbc.php
- tests/DockerImages/5.6/Dockerfile
- tests/DockerImages/7.0/Dockerfile
- tests/DockerImages/7.1/Dockerfile
- tests/DockerImages/7.2/Dockerfile
- tests/DockerImages/7.3/Dockerfile
- tests/DockerImages/7.4/Dockerfile
- tests/DockerImages/8.0/Dockerfile
- tests/DockerImages/8.1/Dockerfile
- tests/DockerImages/8.2/Dockerfile
- tests/DockerImages/8.3/Dockerfile
- xdebug/xdebug.php
- Added default values for some parameters that missed it;
- Updated names of some parameters;
- Updated dockerfiles to make gd extension work.
> Attempt to fix StubsConstantsAndParametersValuesTest::testFunctionsDefaultParametersValue()

- standard/standard_9.php
Rather than adding PHP 7 and PHP 8 to the top here, just remove the line
> get rid of misleading version string

- SPL/SPL_c1.php
It looks like `SplHeap::extract` was accidentally overlooked when the generic type was added.
BTW: There's also an inconsistency between `SplMinHeap` and `SplMaxHeap`. `SplMinHeap` has some of the `SplHeap` methods duplicated, whereas `SplMaxHeap` doesn't have the duplicated methods.
> fix SplHeap::extract phpdoc return type

- standard/basic.php
The problem is that both deprecated functions convert unconditionally between utf-8 and iso-8859-1.
But mb_convert_encoding works differently if the from_encoding parameter is missing:
" If from_encoding is omitted or null, the mbstring.internal_encoding setting will be used if set, otherwise the default_charset setting."
> more accurate replacement for utf8_encode and utf8_decode

- SPL/SPL.php
- tests/TestData/mutedProblems.json
Element is available from PHP 5.1, not 7.0. [1]
The lowest common denominator is 5.3.
[1]: https://github.com/php/php-src/blob/php-5.1.0/ext/spl/spl_array.c#L787
> Fix SPL ArrayObject::__construct(, $flags, $iteratorClass)

- standard/standard_4.php
Add data type to every `setcookie` parameters to reflect its requirements.
```php
<?php
declare(strict_types=1);
// Type Error: setcookie() expects parameter 2 to be string, int given
setcookie('IS_WEBP_SUPPORTED', 1, ['httponly' => true, 'samesite' => 'Lax']);
```
Function `setcookie` requires strict types for every parameter. Current PHPStorm `PhpStorm-231.8109.199/plugins/php-impl/lib/php.jar!/stubs/standard/standard_4.php` does not reflect that, which may results to a fatal in production in case of unaware developer.
> Update types for setcookie parameters

- PhpStormStubsMap.php
- mongodb/BSON/Document.php
- mongodb/BSON/PackedArray.php
- mongodb/BSON/Persistable.php
- mongodb/BSON/Serializable.php
- mongodb/Monitoring/LogSubscriber.php
- mongodb/ReadConcern.php
- mongodb/ReadPreference.php
- mongodb/ServerApi.php
- mongodb/WriteConcern.php
Updates stubs for the latest minor version of ext-mongodb.
Note that I wasn't able to run any checks locally:
```
docker-compose -f docker-compose.yml run -e PHP_VERSION=8.0 test_runner composer cs
WARN[0000] The "PHP_VERSION" variable is not set. Defaulting to a blank string.
[...]
PHP needs to be a minimum version of PHP 7.4.0 and maximum version of PHP 8.1.*.
Current PHP version: 8.3.0RC6.
To ignore this requirement please set `PHP_CS_FIXER_IGNORE_ENV`.
If you use PHP version higher than supported, you may experience code modified in a wrong way.
Please report such cases at https://github.com/PHP-CS-Fixer/PHP-CS-Fixer .
Script php-cs-fixer fix -v --diff --dry-run handling the cs event returned with error code 1
```
Notice how despite me passing `PHP_VERSION` as is done in CI and other …
> Update MongoDB stubs for 1.17

- Core/Core_c.php
https://www.php.net/manual/en/closure.bind.php
should prevent passing unknown classes together with static analysers
> Narrow Closure::bind $newScope param

- Core/Core_c.php
> BackedEnum::from() can also throw TypeError

- .github/workflows/main.yml
- .github/workflows/testLinks.yml
- .github/workflows/testPeclExtensions.yml
This resolves the [`The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2` warning seen](https://github.com/JetBrains/phpstorm-stubs/actions/runs/7505906968) when running Actions.
See also: [actions/checkout changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
> Update actions/checkout to v4

- ds/ds.php
Image that you have a method which returns a generic collection:
```
/**
* @return Vector<Communication>
*/
public function getCollection(): Vector{
return new Vector([new Communication(), new Communication()]);
}
```
And also you have another method where you iterate over that collection:
```
public function test()
{
$list = $this->getCollection();
foreach($collection as $item){
..
}
}
```
If both methods are in the same class, everything works good. But if these classes are in different classes, phpstorm will no understand a time of collection's item inside foreach.
Everything works properly for the Queue collection, but there is problems with other collections. I see that there is a phpdoc for the Queue::getIterator() method:
```
/**
* @return Traversable<TValue>
*/
public function …
```
> php-ds: add missed return types for the getIterator() methods

- redis/Redis.php
threshold accept both int and string.
I'M not sure if a whole update from https://github.com/phpredis/phpredis/blob/5d293245cdd55cc16b8735a788f06d4cb98bf65c/redis.stub.php#L3964 make sense. But it look like there is a big diff between them.
> Fix xTrim threshold parameter

- openssl/openssl.php
OPENSSL_KEYTYPE_EC, an additional array key named "ec", containing the key data is returned. 
Source:
https://www.php.net/manual/en/function.openssl-pkey-get-details.php
> Add missing key `ec` in return for function `openssl_pkey_get_details`

- standard/standard_2.php
In the methods `passthru`, `exec` and `system`, the argument `result_code` was incorrectly named `return_var` in the function description
> Correct the `result_code` argument name

- SPL/SPL.php
ArrayObject:offsetGet should return `TValue|null`
See https://www.php.net/manual/en/arrayobject.offsetget.php#refsect1-arrayobject.offsetget-returnvalues
> fix: ArrayObject::offsetGet return type

- standard/standard_9.php
Several array diff functions had their params changed to use `array` instead of `array1`.  This commit updates the return value _descriptions_ to match both the updated variable names and the manual's textual descriptions
> Update return descriptions of array diff functions

- intl/intl.php
Updating this to match the manual: https://www.php.net/manual/en/spoofchecker.areconfusable.php
This was updated in the manual by php/doc-en#907
> Fix: `Spoofchecker::areConfusable()` `$errorCode` param is int

- Ev/Ev.php
Currently in PHPStorm: 'void' method 'defaultLoop' result used.
According to the documentation it either returns the default loop, or creates + returns it.
> Let EvLoop::defaultLoop() return an EvLoop instance

- .github/workflows/main.yml
Each of these jobs prints a progress bar of the completion of the tasks.  While the composer install usually completes within a few seconds and only logs 4-5 lines of output, the phpunit job takes several minutes and outputs over 800 lines (about 64 kb) of progress bars.  This change removes the printing of progress bars in CI only--local runs are not affected.  This should reduce storage needs and make logs easier to read by humans.
> Hide command progress bars in CI job output

- dom/dom_c.php
Adjusted return type as per the official documentation:
https://www.php.net/manual/en/domnodelist.item.php
> Fix DOMNodeList::item() return type

- Reflection/ReflectionMethod.php
phpstan reports that `getClosure()` may return null and this creates unnecessary false reporting. New versions of PHP don't return null and instead throw an exceptions
> Make ReflectionMethod->getClosure() always return Closure

- json/json.php
The document for `JSON_OBJECT_AS_ARRAY` is not correct.
`JSON_OBJECT_AS_ARRAY` is NOT used by default if `$assoc` parameter is `null`.
See (*PHP 8.3.3*) :
```
php > echo gettype(json_decode('{"foo": "bar"}', associative: null));
object
```
```
php > echo gettype(json_decode('{"foo": "bar"}', associative: null, flags: JSON_OBJECT_AS_ARRAY));
array
```
However, if `$assoc` param is `true`, as per [PHP documenation](https://www.php.net/manual/en/json.constants.php#constant.json-object-as-array), `JSON_OBJECT_AS_ARRAY` is added automatically.
```
php > echo gettype(json_decode('{"foo": "bar"}', associative: true));
array
```
> Fix JSON_OBJECT_AS_ARRAY flag documentation

- yaf/yaf.php
This PR contain fixes for YAF stubs against https://github.com/laruence/yaf/ repo
> Fix yaf stubs

- Core/Core.php
Add documentation for return type value of set_error_handler and error handler chaining based on [PHP documentation](https://www.php.net/manual/en/function.set-error-handler.php).
> Document return type value of set_error_handler and error handler chaining

- SPL/SPL_c1.php
SplDoublyLinkedList has a template type declared but it is not currently referenced in any of the methods.
> Use template type in SplDoublyLinkedList methods

- PhpStormStubsMap.php
- newrelic/newrelic.php
Hi!
We've figured out that the New Relic function `newrelic_set_user_id` was missing in the stubs.
[Here](https://docs.newrelic.com/docs/apm/agents/php-agent/php-agent-api/newrelic_set_user_id/) is the related documentation.
Thanks!
> [newrelic] Add missing "newrelic_set_user_id" function definition

- mongodb/BSON/Document.php
- mongodb/BSON/PackedArray.php
Missing from https://github.com/JetBrains/phpstorm-stubs/pull/1590
The classes `MongoDB\BSON\Document` and `MongoDB\BSON\PackedArray` implement `ArrayAccess` since [ext-mongodb v1.17.0](https://github.com/mongodb/mongo-php-driver/releases/tag/1.17.0) by https://github.com/mongodb/mongo-php-driver/commit/2a3a9d8ce50ce4aa5ce125a2e23cdc5d43e1f625
> MongoDB BSON classes implementing ArrayAccess

- date/date_c.php
Hi @isfedorov,
As reported here https://github.com/JetBrains/phpstorm-stubs/pull/1646#issuecomment-2212413641 I missed one `@throws` annotation.
> Add missing throw tag on `DateTimeImmutable::modify`

- mongodb/BSON/UTCDateTime.php
New method in ext-mongodb 1.20.0
https://www.php.net/manual/en/mongodb-bson-utcdatetime.todatetimeimmutable.php
Added by https://github.com/mongodb/mongo-php-driver/pull/1611
Documented by https://github.com/php/doc-en/pull/3578
> Add `MongoDB\BSON\UTCDateTime::toDateTimeImmutable()`

- PDO/PDO.php
Hi!
Please consider this PR if you think is feasible.
I was getting confused by a warning made in PhpStorm in the PDO fetchAll method, because phpstan was letting me know that it should only return and array and not false.
Looking into [PHP documentation](https://www.php.net/manual/en/pdostatement.fetchall.php) this method should return an array.
Thanks!
> Update PDO fetchAll return type.

- gearman/gearman.php
Fixes the type for `$unique` on a handful of task methods.
This corrects them, as well as an incorrect link in the docs.
---
As you can see below, a small handful already had $unique as `string|null` but the majority did not.
https://github.com/JetBrains/phpstorm-stubs/blob/5686f9ceebde3d9338bea53b78d70ebde5fb5710/gearman/gearman.php#L1510-L1510
https://github.com/JetBrains/phpstorm-stubs/blob/5686f9ceebde3d9338bea53b78d70ebde5fb5710/gearman/gearman.php#L1542-L1542
https://github.com/JetBrains/phpstorm-stubs/blob/5686f9ceebde3d9338bea53b78d70ebde5fb5710/gearman/gearman.php#L1555-L1555
https://github.com/donatj/phpstorm-stubs/blob/5686f9ceebde3d9338bea53b78d70ebde5fb5710/gearman/gearman.php#L1568-L1568
> Fixes types on $unique on Gearman task methods

- hash/hash.php
I noticed that the return statements for the hash package incorrectly discuss `raw_output` when it should be `binary` as this is the current name of the parameter and has been for some time.
This can be verified by looking above/below these corrections a couple lines on each occurrence or double checking the official PHP documentation.
> fix: hash module return statement from raw_output to binary

- pam/pam.php
Related to https://github.com/phpstan/phpstan/issues/10499
According to
https://github.com/amishmm/php-pam/blob/master/README
https://github.com/amishmm/php-pam/blob/master/pam.stub.php
The error param is optional.
> Fix error default value for pam functions

- tests/TestData/Providers/Stubs/PhpCoreStubsProvider.php
Try to fix https://github.com/JetBrains/phpstorm-stubs/actions/runs/10575852193/job/29300999760 (failure introduced in #1665).
I don't manage to run tests locally.
> Add stubs for FrankenPHP

- mysqli/mysqli.php
References: 
1. https://github.com/php/php-src/commit/4f58d5b0df823dbdc4e629d98b3d564050e9173e#diff-ce0c5eab4a0f9d6523a97713c8bfdff9f1067e3955c745902cbd3cb3a187cbefL142
2. https://www.php.net/manual/en/mysqli.store-result.php
> 8.4.0 | Passing the mode parameter is now deprecated. The parameter has had no effect as of PHP 8.1.0.
> mysqli_store_result second parameter is deprecated in PHP 8.4

- dom/dom_c.php
References:
1. https://github.com/php/php-src/commit/d9eb3783bdd6947a635f132f8c240de8f40e8704#diff-7ee66c4f1536ac84dc5bbff1b8312e2eef24b974b3e48a5c5c2bcfdf2eb8f3ceR17
2. https://wiki.php.net/rfc/deprecations_php_8_4
> DomImplementation::getFeature is removed in PHP 8.4

- PDO/PDO.php
Hi all,
Please consider this change to the PDOStatement::fetchAll stub.
Based on the [PHP documentation](https://www.php.net/manual/en/pdostatement.fetchall.php) it should be possible for this method to throw a PDOException.
I've also made a minor update to the return description as returning `false` was removed in https://github.com/JetBrains/phpstorm-stubs/pull/1656
Thanks!
> Update PDOStatement::fetchAll @throws phpdoc

- dom/dom_c.php
Reference: https://www.php.net/manual/en/class.domnode.php
> 8.0.0 | The unimplemented methods DOMNode::compareDocumentPosition(), DOMNode::isEqualNode(), DOMNode::getFeature(), DOMNode::setUserData() and DOMNode::getUserData() have been removed.
> DomNode unimplemented methods have been removed in PHP 8.0

- imagick/imagick.php
See: 
- https://www.php.net/manual/en/imagick.writeimagefile.php
- https://www.php.net/manual/en/imagick.writeimagesfile.php
- https://pecl.php.net/package-info.php?package=imagick&version=3.2.0b1#:~:text=Added%20additional%20parameter%20to%20writeImageFile%20to%20allow%20setting%20format
> Imagick::writeImageFile supporting format parameter

- relay/Cluster.php
- relay/Relay.php
Bumps the stubs to [v0.9.0](https://github.com/cachewerk/relay/releases/tag/v0.9.0).
> Update Relay stubs to v0.9.0

- PDO/PDO.php
- PhpStormStubsMap.php
these are taken from the documentation in https://www.php.net/manual/en/class.pdo-pgsql.php, which can be sourced back to https://github.com/php/php-src/blob/master/ext/pdo_pgsql/pgsql_driver.stub.php
> adds stubs for Pdo\Pgsql

- standard/standard_8.php
cf https://www.php.net/manual/en/function.ob-start.php
ob_start is 
```
ob_start(?callable $callback = null, int $chunk_size = 0, int $flags = PHP_OUTPUT_HANDLER_STDFLAGS): bool
```
> Update ob_start signature

- redis/RedisCluster.php
* Fix RedisCluster class constructor parameter
* rename named argument `readTimeout` to `read_timeout`
* fix default value
* add type hinting
* Remove non-existent constants in Redis Cluster class
ref. [phpredis/redis_cluster.stub.php at develop · phpredis/phpredis](https://github.com/phpredis/phpredis/blob/develop/redis_cluster.stub.php)
issues
* [Invalid named argument for RedisCluster constructor : WI-80445](https://youtrack.jetbrains.com/issue/WI-80445/Invalid-named-argument-for-RedisCluster-constructor)
* [There are non-existent constants in the RedisCluster class : WI-80446](https://youtrack.jetbrains.com/issue/WI-80446/There-are-non-existent-constants-in-the-RedisCluster-class)
> Fix constructor parameter and Remove non-existent constants in Redis Cluster class

- LuaSandbox/LuaSandbox.php
LuaSandboxFunction::call can be called [without any parameter](https://www.php.net/manual/en/luasandboxfunction.call.php), but it generated error as it was before
> fix LuaSandboxFunction::call notation

- tests/DockerImages/peclExtensions/Dockerfile
Commented out the installation and enabling of the MongoDB extension in the PECL extensions Dockerfile. This change  intended to temporarily exclude MongoDB for testing or compatibility reasons. Other extensions remain unaffected.
> Disable MongoDB extension in test Dockerfile

- Core/Core.php
- fileinfo/fileinfo.php
- json/json.php
- standard/standard_8.php
Added the missing `#[Pure(true)]` attribute to some functions that have side effects but whose return value is important.
We could add it to more functions, but this PR only marks functions that are well-known and whose return value is obviously something you should use.
> Add `#[Pure(true)]` to some functions where the return value is important

- hash/hash.php
The params description at https://www.php.net/function.hash-equals has been changed in https://github.com/php/doc-en/pull/2821 and I think it should also be changed here.
> Update hash_equals params description

- memcache/memcache.php
Hi @isfedorov 
It's not easy but I tried to fix/improve the memcache stubs.
- All the `memcache_` function should have the memcache instance as first param.
- Most of the `memcahce_` params were not documented (I copy pasted the instance doc)
- Some of the `Memcache::` methods were not documented
> Fix memcache definition

- gnupg/gnupg.php
"The signature. To verify a clearsigned text, set signature to false." https://www.php.net/manual/en/function.gnupg-verify.php
gnupg_verify() below already has it.
> Add false to gnupg::verify $signature

- redis/RedisCluster.php
`RedisCluster->rawCommand()` method stub currently indicated that exactly 3 parameters would be required, but it actually requires 2 or more arguments
Code like
```
$redisCluster->rawCommand($key, 'expire', $key, $timeout, $mode);
```
gets highlighted with inspection warning
```
Method RedisCluster::rawCommand() invoked with 5 parameters, 3 required
```
although perfectly valid. Note that the original method name is not camelCase but all lower case as well (verified via reflection)
See the [official phpredis stub](https://github.com/phpredis/phpredis/blob/46b8074216fcf862db7769270653ec1465bca77e/redis_cluster.stub.php#L727) for comparison.
This PR addresses [WI-81080](https://youtrack.jetbrains.com/issue/WI-81080)
> Fix variable arguments on RedisCluster::rawCommand()

- standard/standard_1.php
Linked to this issue : [WI-80919](https://youtrack.jetbrains.com/issue/WI-80919)
As we can see in this pull request, PHP doesn't tolerate null as an array in implode/join functions : https://github.com/php/php-src/pull/12683
> Remove second parameter incorrect nullable

- standard/standard_1.php
Reverts JetBrains/phpstorm-stubs#1728
I made a mistake when accepted these changes. I checked what reflection returns and what is in the [PHP source code](https://github.com/search?q=repo%3Aphp%2Fphp-src%20implode&type=code). It turns out that $array is indeed an optional parameter and it's default value is null.
`<?php`
`namespace B;`
`use ReflectionFunction;`
`$reflection = new ReflectionFunction('implode');`
`$parameters = $reflection->getParameters();`
`foreach ($parameters as $param) {`
`    echo "Parameter: " . $param->getName();`
`    echo "\nRequired: " . ($param->isOptional() ? "No" : "Yes");`
`    echo "\n\n";`
`}`
Output:
`Parameter: separator`
`Required: Yes`
`Parameter: array`
`Required: No`
> Revert "Remove second parameter incorrect nullable"

- redis/RedisCluster.php
As per [phpredis docs](https://github.com/phpredis/phpredis/blob/develop/cluster.md#main-command-loop) nearly every cluster method can lead to a `RedisClusterException`, depending on the state of the queried cluster (i.e. cluster in failover, nodes down, ...).
This is not easily recognizable to developers, especially when relying on the correctnes of the method declarations and their `@throws` annotation.
This PR tries to fix that, introducing `@throws RedisClusterException` on any method, that communicates with the connected cluster.
> feat(exception)!: declare RedisClusterException on most methods

- PDO/PDO.php
HI @isfedorov,
Most of PDO methods are throwing an exception if `PDO::ERRMODE_EXCEPTION` mode is set.
I tried to update all method which could have a failure.
Example
https://www.php.net/manual/en/pdo.exec.php
```
Errors/Exceptions[ ¶](https://www.php.net/manual/en/pdo.exec.php#refsect1-pdo.exec-errors)
Emits an error with level [E_WARNING](https://www.php.net/manual/en/errorfunc.constants.php#constant.e-warning) if the attribute [PDO::ATTR_ERRMODE](https://www.php.net/manual/en/pdo.constants.php#pdo.constants.attr-errmode) is set to [PDO::ERRMODE_WARNING](https://www.php.net/manual/en/pdo.constants.php#pdo.constants.errmode-warning).
Throws a [PDOException](https://www.php.net/manual/en/class.pdoexception.php) if the attribute [PDO::ATTR_ERRMODE](https://www.php.net/manual/en/pdo.constant …
```
> Add PDO method can throws PDOException

- Core/Core.php
These functions won't return NULL as it was saying in the documentation.
The only possible return values are true or false.
> Update Core.php docblock for property_exists and trait_exists functions

- dom/dom_c.php
See https://github.com/phpstan/phpstan/issues/13076
This reverts #1741
From the PHP docs: https://www.php.net/manual/en/class.domnode.php#domnode.props.attributes
> A [DOMNamedNodeMap](https://www.php.net/manual/en/class.domnamednodemap.php) containing the attributes of this node (if it is a [DOMElement](https://www.php.net/manual/en/class.domelement.php)) or [null](https://www.php.net/manual/en/reserved.constants.php#constant.null) otherwise.
So, on `\DOMElement` it's correct to override and mark it as not nullable.
> Revert #1741 - \DOMElement::$attributes is never null

- date/date_c.php
Hi,
- In php stubs the method doesn't exists https://github.com/php/php-src/blob/master/ext/date/php_date.stub.php#L331
- No setter are defined in DateTimeInterface since the behavior is different for mutable and immutable classes
> Remove DateTimeInterface::setMicrosecond

- .php-cs-fixer.php
This PR excludes files with lint errors so the job is green on the regular.
I would also suggest setting up required checks on the tests and CS jobs to ensure that PRs are not merged over a red CI.
> Fix CS errors

- eio/eio.php
cc @isfedorov 
All the descriptions are `returns request resource on success, or false on failure.`.
> Use more precise return type for eio_

- amqp/amqp.php
I took
- https://github.com/php-amqp/php-amqp/blob/latest/stubs/AMQPChannel.php
- https://github.com/php-amqp/php-amqp/blob/latest/stubs/AMQPConnection.php
- https://github.com/php-amqp/php-amqp/blob/latest/stubs/AMQPEnvelope.php
- https://github.com/php-amqp/php-amqp/blob/latest/stubs/AMQPExchange.php
- https://github.com/php-amqp/php-amqp/blob/latest/stubs/AMQPQueue.php
for reference
> Fix amqp stub

- xml/xml.php
When looking at the doc of those xml methods
https://www.php.net/manual/en/function.xml-set-element-handler.php
There is no mention of signature changes from `callable` to `callable|string|null`.
So, the signature for handlers always was `callable|string|null` from the beginning.
> Fix xml_ handler signature

- dom/dom_c.php
The description is
```
The [DOMDocument](https://www.php.net/manual/en/class.domdocument.php) object associated with this node, or [null](https://www.php.net/manual/en/reserved.constants.php#constant.null) if this node is a [DOMDocument](https://www.php.net/manual/en/class.domdocument.php)
```
so ownerDocument is always null for a DomDocument.
This is by design, as the document is the root container and doesn't have an owner document.
> Restrict type of DomDocument::ownerDocument

- standard/standard_9.php
See https://3v4l.org/3TXPC#veol
I dunno if it's something which should be documented by phpstorm...
> Version compare returns null on PHP 7.4

- standard/standard_10.php
According to the [PHP docs](https://www.php.net/manual/en/function.request-parse-body.php#refsect1-function.request-parse-body-errors):
> When the request body is invalid, according to the Content-Type header, a [RequestParseBodyException](https://www.php.net/manual/en/class.requestparsebodyexception.php) is thrown.
>
> A [ValueError](https://www.php.net/manual/en/class.valueerror.php) is thrown when options contains invalid keys, or invalid values for the corresponding key.
> Add @throws for request_parse_body()

- standard/standard_9.php
As per [the PHP documentation](https://www.php.net/manual/en/function.array-combine.php#refsect1-function.array-combine-errors):
> As of PHP 8.0.0, a [ValueError](https://www.php.net/manual/en/class.valueerror.php) is thrown if the number of elements in keys and values does not match. Prior to PHP 8.0.0, a [E_WARNING](https://www.php.net/manual/en/errorfunc.constants.php#constant.e-warning) was emitted instead.
I consequently update the stub.
> Add array_combine thrown exception for php >= 8

- date/date_c.php
See:
- https://github.com/php/php-src/blob/e48099a03c677bea5d0c615cefcab094f8b5253b/ext/date/php_date.stub.php#L361-L362
- https://github.com/php/php-src/blob/e48099a03c677bea5d0c615cefcab094f8b5253b/ext/date/php_date.stub.php#L564-L565
> Fix createFromInterface return type

- .github/workflows/main.yml
- Core/Core.php
- meta/attributes/Pure.php
- standard/standard_8.php
- standard/standard_9.php
This PR is based on *my* interpretation of the documentation on the attribute that `Pure(true)` means a function:
* Does **not** have any side effects on external state or the supplied parameters
* **and** the result depends on some external state outside of the supplied parameters.
This contradicts with the interpretation in #1724 by @zonuexe which was accepted:
> Added the missing `#[Pure(true)]` attribute to some functions **that have side effects** [emphasis mine] but whose return value is important.
The reasoning for each change is documented in the commit messages.
As such it reverts some of the changes made in that PR. If my interpretation is wrong then reject this, but please improve the documentation.
> Fix bad `Pure` attributes

- meta/.phpstorm.meta.php
- standard/standard_8.php
Prior to this change, PHPStorm's type inference would always return `mixed` for the return types of `array_first` and `array_last`. By upgrading the input types to templates, we implicitly enforce the use of a more advanced generics type provider that deals with array elements correctly.
> Force array_first/-last input types through template

- standard/_types.php
For some reason https://github.com/JetBrains/phpstorm-stubs/pull/1280 changed the return type of `Generator::current()` from `TYield|null` to `TYield`, which is not correct.
Similarly, `Generator::key()` can return `null` as well.
For reference: https://3v4l.org/aSMe8
```php
$generator = (function () {
yield 0;
})();
var_dump($generator->current()); // 0
var_dump($generator->key()); // 0
$generator->next();
var_dump($generator->current()); // null
var_dump($generator->key()); // null
```
> Fix missing null return type for Generator::current() & Generator::key()
