JetBrains/phpstorm-stubs

- mysqli.php
Related to https://youtrack.jetbrains.com/issue/WI-20880
> mysqli_stmt_get_result: Fixed wrong doc type

- session.php
Related to https://youtrack.jetbrains.com/issue/WI-26566
> Added session_abort and session_reset stubs

- standard_6.php
Related to https://youtrack.jetbrains.com/issue/WI-26410
> Added additional stream_context_set_option signature

- posix.php
Related to https://youtrack.jetbrains.com/issue/WI-24675
> Fixed posix_isatty signature

- Reflection.php
Related to https://youtrack.jetbrains.com/issue/WI-23096
> Added ReflectionFunctionAbstract isVariadic & isGenerator stubs

- standard_4.php
Related to https://youtrack.jetbrains.com/issue/WI-19134
> Fixed header signature

- intl.php
Related to https://youtrack.jetbrains.com/issue/WI-20989
> Added additional IntlCalendar::set signature

- SPL_c1.php
Add \SplFileObject::fread
http://php.net/manual/en/splfileobject.fread.php
Cheers
> Added SplFileObject::fread

- mysql.php
Based on PHP_DEP_FALIAS declarations in PHP sources.
> Mark deprecated mysql functions

- standard_2.php
see https://youtrack.jetbrains.com/issue/WI-27194
> WI-27194 - Fixed http_build_query signature

- imagick.php
see https://youtrack.jetbrains.com/issue/WI-27356
> WI-27356 - Fixed Imagick::mergeImageLayers signature

- amqp.php
This PR adds stubs for https://pecl.php.net/package/amqp
related to https://youtrack.jetbrains.com/issue/WI-15322
> Pecl AMQP stubs

- Reflection.php
Related to https://youtrack.jetbrains.com/issue/WI-14313
> Added ReflectionProperty::setValue second signature

- oci8.php
http://php.net/manual/en/oci-lob.writetemporary.php
> Method name case fix

- intl.php
See: http://php.net/manual/fr/intldateformatter.settimezone.php
> Fix IntlDateFormatter::setTimeZone() method case

- curl_d.php
http://php.net/manual/en/function.curl-setopt.php
https://youtrack.jetbrains.com/issue/WI-27882
> Added missing CURLOPT_KEYPASSWD

- PDO.php
Update so stub shows additional parameters can be used especial the second parameter to set fetch mode.
> Update to PDO::query stub to document the 2nd and follow parameters options

- standard_6.php
> Update standard_6.php, fixed typo

- SplType.php
http://php.net/manual/en/book.spl-types.php
> Support for SplType extension

- standard_4.php
I've copied the function signature of printf in standard_2.php.
Relevant YouTrack issue: https://youtrack.jetbrains.com/issue/WI-27817
The contributor agreement has been sent to contribute@jetbrains.com.
> WI-27817 Fix var_dump() variadic arguments

- yaml.php
I sent my signed CLA to contribute@jetbrains.com
> Added yaml stub

- newrelic.php
> Added newrelic stub

- dom_c.php
https://youtrack.jetbrains.com/issue/WI-28837
I hope this is the correct way to add the missing optional parameters.
> Proposed fix for WI-28837

- Reflection.php
- libxml.php
- snmp.php
- standard_4.php
- xsl.php
This PR adds this missing [isVariadic to ReflectionParameter](http://php.net/manual/en/reflectionparameter.isvariadic.php) and fixes some missing `@since` annotations.
> Added ReflectionParameter::isVariadic

- mongodb.php
Stubs for [new Mongodb extension](http://docs.php.net/manual/en/set.mongodb.php) according to [New PHP and HHVM Drivers](https://www.mongodb.com/blog/post/call-feedback-new-php-and-hhvm-drivers) and [mongodb docs](https://docs.mongodb.org/ecosystem/drivers/php/).
Please, let me know if my PR good enough and if it could be merged in near future. I haven't submitted contributor license agreement yet, but I will sign it after your approval.
Thanks
> Add new mongodb extension

- mysqli.php
As per https://twitter.com/codemasher/status/662063737919139840
> Added mysqli_stmt::$error_list

- standard_9.php
A copy of #63 which can be merged.
> WI-29921: add realpath_cache_get() and realpath_cache_size(). Extends and closes #63.

- Reflection.php
- standard_4.php
- standard_defines.php
Fixed WI-29455 isAnonymous() method not found in class ReflectionClass	0fb884b
Fixed WI-27705 INI_SCANNER_TYPED constant is not recognised
> ReflectionClass::isAnonymous() method and INI_SCANNER_TYPED constant ReflectionFunctionAbstract::isGenerator

- standard_defines.php
This fixes https://youtrack.jetbrains.com/issue/WI-30119
> Added INI_SCANNER_TYPED

- imagick.php
https://youtrack.jetbrains.com/issue/WI-31251
> Fix WI-31251

- apcu.php
see https://youtrack.jetbrains.com/issue/WI-28823
> Resolve WI-28823 Add APCu stubs

- mongodb.php
- Manager::executeBulkWrite. Remove the default value for $bulk
- Server::executeBulkWrite. Update comment and add parametr $writeConcern
- ReadPreference. Add function getMode and getTagSets
- Add class ReadConcern
- UTCDatetime::toDateTime. Update comment
> Fixes and improvements on MongoDB classes

- date.php
p.s. Contributor license agreement submitted
> [phpDoc] Added `false` type to `@return` section

- mysqli.php
Add support for function mysqli_ssl_set()
> Add support for function mysqli_ssl_set()

- gearman.php
https://youtrack.jetbrains.com/issues/WI-32716
> Update gearman stub with GearmanWorker->setId

- password.php
https://youtrack.jetbrains.com/issue/WI-33065
> Fixed wrong password_needs_rehash return annotation

- mongodb.php
> Fixing wrong stubs on \MongoDB\BSON\Binary

- date_c.php
Added return of DateTime|boolean to createFromFormat functions. 
See: http://php.net/manual/en/datetime.createfromformat.php#refsect1-datetime.createfromformat-returnvalues
> Fix return value of createFromFormat

- mongo.php
\MongoCollection::findOne() has a third parameter `options` ([check docs](http://www.php.net/manual/en/mongocollection.findone.php)).
> Fixing wrong stubs on \MongoCollection

- Redis.php
Update the Redis stub from ukko/phpredis-phpdoc
Related YT issue: WI-30713
If necessary I can pare down the diffs to functional changes only, but I thought that since this stub is based off of ukko/phpredis-phpdoc anyway it was advisable to start bringing it back into sync
> Update Redis stub

- standard/intl.php
- standard/standard_4.php
Commits fix three invalid functions with parameters by reference.
The fix is necessary to create tests for: https://youtrack.jetbrains.com/issue/WI-33303
> Update functions with pass by reference parameters

- standard/dom_c.php
see http://php.net/manual/en/domnodelist.item.php
> fix return of DOMNodelist::item

- standard/standard_9.php
Fix for https://youtrack.jetbrains.com/issue/WI-34156
> array_sum & array_product: fix return phpdoc

- standard/standard_3.php
getenv manual page is not yet updated, but you can find information here:
http://php.net/manual/en/migration71.changed-functions.php
> Update getenv to match php 7.1

- standard/standard_8.php
See https://youtrack.jetbrains.com/issue/WI-32323
> metaphone() correction

- standard/standard_7.php
Added all the available flags for the glob() function
> Added all flags for glob()

- standard/Core_c.php
See http://php.net/manual/en/exception.construct.php
> Update Core_c Exception Constructor docBlock

- standard/memcache.php
* https://youtrack.jetbrains.com/issue/WI-33799
> Fix memcache increment documentation stub error

- standard/standard_3.php
https://youtrack.jetbrains.com/issue/WI-34757
https://youtrack.jetbrains.com/issue/WI-34400
> Fix default params for getopt() function

- standard/mysql.php
http://php.net/manual/en/function.mysql-num-rows.php
> mysql_num_rows() is also deprecated

- couchbase/couchbase.php
- couchbase/toplevel.php
Today we release 2.3.0 version of extension with updated API documentation
> Update Couchbase stubs to 2.3.0

- ext-libsodium.php
https://github.com/jedisct1/libsodium-php/issues/77
As noted in the original version in Halite, I'm releasing this under WTFPL/CC0 but I will sign a contributor agreement too.
> Create stub for libsodium

- curl/curl_d.php
- standard/standard_5.php
http://php.net/ChangeLog-5.php#5.5.0
> WI-28374 is_callable() WI-31161 CURLOPT_RESOLVE  CURL PHP 5.5 missing constants

- standard/standard_4.php
Added the defaults from the documentation instead of nulls
> added better default values

- intl/intl.php
issue: https://youtrack.jetbrains.com/issue/WI-35863
tests: https://3v4l.org/b6dB9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jetbrains/phpstorm-stubs/194)
> fix PHPDoc for "grapheme_substr()"

- redis/RedisCluster.php
Based on https://github.com/zgb7mtr/phpredis_cluster_phpdoc
> Add RedisCluster

- standard/standard_defines.php
https://youtrack.jetbrains.com/issue/WI-36274
> [WI-36274] fix FNM_NOESCAPE and FNM_PATHNAME values

- imagick/imagick.php
copied from http://php.net/manual/en/imagick.compositeimage.php
> compositeImage: $composite doc

- mongodb/mongodb.php
Updates `MongoDB\Driver\Manager`.
ref: http://php.net/manual/en/class.mongodb-driver-manager.php
> update MongoDB\Driver\Manager stub

- mongodb/mongodb.php
Updates `MongoDB\Driver\Server stub`.
ref: http://php.net/manual/en/class.mongodb-driver-server.php
> update MongoDB\Driver\Server stub

- redis/Redis.php
- add persistent_id param to pconnect/popen
- update description and code example
See
https://github.com/phpredis/phpredis/tree/3.1.2#pconnect-popen
> Update pconnect/popen params in Redis.php

- dom/dom_c.php
See http://php.net/manual/en/domdocument.savexml.php
> DOMDOcument::saveXML: add DOMNode typehint 

- date/date_c.php
https://github.com/php/php-src/commit/55626549d81d0feadb1d160be78fcf2b898a48cc
https://youtrack.jetbrains.com/issue/WI-36709
https://3v4l.org/sRiqF
> DateInterval has microseconds since PHP 7.1

- rar/rar.php
> Add RarArchive stub with correct folder

- standard/standard_8.php
> The key can either be an integer or a string.
http://php.net/manual/en/language.types.array.php
> Change key() and array_search() return types

- com/com.php
> Added definitions from the COM library

- standard/standard_6.php
Fix to match the manual:
http://php.net/manual/en/function.fgetcsv.php
> Fix fgetcsv() default values

- Phar/Phar.php
- SPL/SPL.php
- SPL/SPL_c1.php
- SQLite/SQLite.php
- SimpleXML/SimpleXML.php
- http/http.php
- imagick/imagick.php
- mongo/mongo.php
- Removed unneeded implements from Iterators.
- Fixed default parameters for constructors.
- Updated/fixed phpdocs.
> Fix iterators and update docs

- http/http3.php
Partial implementation of the PECL HTTP extension, with the rest coming soon
> Implements PECL HTTP v3.x

- standard/fann.php
issue: https://youtrack.jetbrains.com/issue/WI-34445
> fann stub added to standart

- gearman/gearman.php
Added missed function \GearmanClient::ping
https://github.com/hjr3/pecl-gearman
> \GearmanClient::ping

- CONTRIBUTING.md
> Fix: Typos

- fileinfo/fileinfo.php
- mime_magic/mime_magic.php
-> https://bugs.php.net/bug.php?id=71367
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jetbrains/phpstorm-stubs/252)
> "claim mime_content_type is deprecated"

- SimpleXML/SimpleXML.php
Following on the awesome change in WI-15760 this adds the Countable interface to fix WI-28138 and WI-38110 so that you can invoke count($aSimpleXmlElement).
> Make SimpleXMLElement Countable

- tokenizer/tokenizer.php
This PR
💁‍♂️ For reference, see:
* http://php.net/manual/en/function.token-get-all.php#refsect1-function.token-get-all-parameters
* https://3v4l.org/TKWdk
> Enhancement: Define TOKEN_PARSE

- oauth/oauth.php
Title says it all... documentation changes only
> Add thrown exceptions to OAuth

- Reflection/Reflection.php
ReflectionClass: add getReflectionConstant and getReflectionConstants method signatures.
> ReflectionClass: add getReflectionConstant and getReflectionConstants

- mysqli/mysqli.php
> fix reference to allow validation of multiple params

- SPL/SPL_c1.php
- Fix SplFileObject constructor parameters to have the correct default values
- Update PHPDocs for constructor and class constants
> Fix SplFileObject constructor parameters

- imagick/imagick.php
Updated Imagick stubs, until version 3.4.3
**NOTE** A lot of functions aren't documented on php.net, so I extracted the function description and arguments from the Changelog and C sourcecode
This is my first time contributing to the PHPStorm stubs, so if something is wrong, please let me know!
> Updating Imagick stubs WI-38010

- standard/standard_2.php
Fixes https://youtrack.jetbrains.com/issue/WI-36692
> Fix default values of PHP str_pad

- apcu/apcu.php
> apcu_add() fix

- mysqli/mysqli.php
Make functions accept variadic parameters per php documentation.  Add more complete docs to mysqli_stmt_bind_param
http://php.net/manual/en/mysqli-stmt.bind-param.php
> WI-6468 Update mysqli bind_param signatures

- Core/Core.php
- Core/Core_c.php
- Reflection/Reflection.php
- SPL/SPL.php
- SPL/SPL_f.php
- dom/dom_c.php
- ftp/ftp.php
- gd/gd.php
- json/json.php
- mbstring/mbstring.php
- openssl/openssl.php
- xml/xml.php
- zlib/zlib.php
Based on changelog, parameters & types directly from C source - none of these changes is documented. :/
http://php.net/ChangeLog-7.php#7.2.0
> PHP 7.2 additions

- solr/Documents/SolrDocument.php
- solr/Documents/SolrDocumentField.php
- solr/Documents/SolrInputDocument.php
- solr/Exceptions/SolrClientException.php
- solr/Exceptions/SolrException.php
- solr/Exceptions/SolrIllegalArgumentException.php
- solr/Exceptions/SolrIllegalOperationException.php
- solr/Exceptions/SolrMissingMandatoryParameterException.php
- solr/Exceptions/SolrServerException.php
- solr/Queries/SolrCollapseFunction.php
- solr/Queries/SolrDisMaxQuery.php
- solr/Queries/SolrModifiableParams.php
- solr/Queries/SolrParams.php
- solr/Queries/SolrQuery.php
- solr/Responses/SolrGenericResponse.php
- solr/Responses/SolrPingResponse.php
- solr/Responses/SolrQueryResponse.php
- solr/Responses/SolrResponse.php
- solr/Responses/SolrUpdateResponse.php
- solr/SolrClient.php
- solr/Utils/SolrObject.php
- solr/Utils/SolrUtils.php
- solr/constants.php
- solr/functions.php
Hi, 
I added the stubs for the Solr extension as requested in this ticket: https://youtrack.jetbrains.com/issue/WI-662
Let me know if you need any changes or info.
> Add stubs for PECL Solr 2.4.0

- standard/standard_0.php
The default is ENT_COMPAT | ENT_HTML401.
http://php.net/manual/en/function.htmlspecialchars.php
> Change default htmlspecialchars $flags parameter

- date/date.php
Reference http://php.net/manual/en/function.date.php
> Fix date() $timestamp default value

- date/date_c.php
It throws on bad inputs just like DateTime constructor.
I've reported this to php.net too.
> Update DateTimeImmutable constructor

- redis/Redis.php
https://youtrack.jetbrains.com/issue/WI-30713
> fixed return types of several methods in Redis.php (WI-30713)

- imagick/imagick.php
I'm sure there are plenty more missing @throws tags, but these are the ones I've ran into personally.
> Added some missing @throws tags and fixed a return description

- Reflection/Reflection.php
https://youtrack.jetbrains.com/issue/WI-40955
> Add lost method ReflectionClassConstant::getName()

- Reflection/Reflection.php
Reported on php.net as well:
https://bugs.php.net/bug.php?id=76060
> Fix getDocComment() return values

- sync/sync.php
Reference https://youtrack.jetbrains.com/issue/WI-40908
> Add new stub for sync PECL extension

- Parle/ErrorInfo.php
- Parle/Lexer.php
- Parle/LexerException.php
- Parle/Parser.php
- Parle/ParserException.php
- Parle/RLexer.php
- Parle/RParser.php
- Parle/Stack.php
- Parle/Token.php
Added the classes for Parle extension so we can autocomplete it.
Issue is https://youtrack.jetbrains.com/issue/WI-40970
> Added support for Parle extension

- mysqli/mysqli.php
http://php.net/manual/ru/mysqli-result.fetch-object.php
> Default $class_name to stdClass

- mysqli/mysqli.php
...this has caused a bit of confusion to me so I thought I could just fix it right away. Hope it helps.
> Fixed description of mysqli_poll so it is in sync with mysqli::poll and the manual

- gd/gd.php
WI-41710 Added php7.2 GD functions
> WI-41710 Added php7.2 GD functions

- date/date_c.php
- mbstring/mbstring.php
- openssl/openssl.php
- session/session.php
- standard/standard_0.php
updated meregi_replace, openssl_open, session_set_save_handler, get_html_translation_table signatures
>  updated function signatures, added missing methods in "date" extension

- .travis.yml
- Core/Core_c.php
- Phar/Phar.php
- Reflection/Reflection.php
- SPL/SPL_c1.php
- composer.json
- gd/gd.php
- sodium/sodium.php
- tests/PHPReflectionParser.php
- tests/StubParser.php
- tests/TestStubs.php
- tests/docker-compose.yml
- tests/mutedProblems.json
- tests/verifier.php
- xmlreader/xmlreader.php
- xmlwriter/xmlwriter.php
The tests verify the correctness of stubs (via PHPDoc parser) and their current state checking via reflection mechanism against php:latest docker image.
> Provide tests for PhpStorm stubs

- Reflection/Reflection.php
https://secure.php.net/manual/en/reflectionclass.getparentclass.php
> Add `false` as possible return type of ReflectionClass::getParentClass

- radius/radius.php
Started adding Radius functions
> WI-38483 Started working on Radius functions

- mysqli/mysqli.php
Fixes https://youtrack.jetbrains.com/issue/WI-39268
> Fixed mysqli::rollback to match the docs

- memcached/memcached.php
http://php.net/manual/en/memcached.setsaslauthdata.php
> add setSaslAuthData func

- json/json.php
Fixes https://youtrack.jetbrains.com/issue/WI-42919
> Fix return type of json_encode

- intl/intl.php
Source: https://github.com/cataphract/PECL-intl/blob/8869e840b06dfd8870129fb18bbe4cc6353379e2/php_intl.c#L342-L345
> Adds missing parameter to datefmt_set_timezone

- filter/filter.php
- fpm/fpm.php
- gd/gd.php
- json/json.php
WI-42885 Updated stubs with 7.3.0 changes (partly)
> WI-42885 Updated stubs with 7.3.0 changes (partly)

- sodium/sodium.php
- tests/mutedProblems.json
> sodium_memzero() - removed invalid param $length

- uopz/uopz.php
I added the missing functions and constants from here: http://php.net/manual/en/ref.uopz.php
> Add functions and constants of the uopz extension

- hash/hash.php
Fix hash_hmac_algos return type ([Source](http://php.net/manual/en/function.hash-hmac-algos.php)).
> hash_hmac_algos

- memcached/memcached.php
Duplicated constant & function definition.
> Remove duplicated definitions from Memcached class

- SPL/SPL.php
Duplicate is at https://github.com/JetBrains/phpstorm-stubs/blob/db07f4569db610bcd6124f8d684d9f9315cd983a/Core/Core.php#L1096-L1103 with phpdoc.
> Remove duplicate is_iterable()

- mysqli/mysqli.php
-> http://php.net/manual/en/mysqli.stmt-init.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jetbrains/phpstorm-stubs/409)
> [+]: fix for "mysqli_stmt_init"

- mysql_xdevapi/mysql_xdevapi.php
- redis/Redis.php
I am adding mysql_xdevapi extension. It is a new extension that allows Mysql to store document
> adding mysql_xdevapi stub

- mysqli/mysqli.php
mysqli_result close and free_result are the same as free, updated the doc comments per the PHP documentation - https://secure.php.net/manual/en/mysqli-result.free.php
> Add docs for mysqli_result close and free_result

- mongodb/mongodb.php
Add methods from 1.2.0 driver version
> Update mongodb.php (WI-43350)

- mongodb/mongodb.php
Issue [WI-43476](https://youtrack.jetbrains.com/issue/WI-43476)
Changes: 
- MongoDB subclasses & interfaces for >1.2.0 version
- minor fixes
> Mongodb (WI-43476)

- redis/RedisCluster.php
Adds reference to the RedisClusterException class that is thrown in the RedisCluster constructor
> Add RedisClusterException

- redis/RedisCluster.php
Please see the definition:  https://github.com/phpredis/phpredis/blob/cd6ebc6d7f56ef652cb1dbe5e02126e95aa30156/redis.c#L725
> Update RedisCluster Options for OPT_SLAVE_FAILOVER

- Reflection/Reflection.php
Added @throws ReflectionException to stub for ReflectionClass::getMethod()
> WI-44153 Added @throws ReflectionException to stub for ReflectionClass:getMethod()

- bcmath/bcmath.php
See [WI-43998](https://youtrack.jetbrains.com/issue/WI-43998)
> Update bcmath stub

- pthreads/pthreads.php
See issue [WI-44013](https://youtrack.jetbrains.com/issue/WI-44013)
> Update pthreads stub based on latest docs (v3.1.6)

- standard/standard_9.php
https://wiki.php.net/rfc/array_key_first_last
https://secure.php.net/array_key_first
https://secure.php.net/array_key_last
https://youtrack.jetbrains.com/issue/WI-44320
> [WI-44320] add array_key_first, array_key_last (PHP 7.3)

- standard/standard_5.php
See https://secure.php.net/is_countable and https://wiki.php.net/rfc/is-countable
https://youtrack.jetbrains.com/issue/WI-44319
> [WI-44319] add is_countable (PHP 7.3)

- tests/PHPReflectionParser.php
- tests/StubParser.php
- tests/TestStubs.php
- tests/mutedProblems.json
> Add tests for interfaces

- redis/Redis.php
https://youtrack.jetbrains.com/issue/WI-30713
https://github.com/phpredis/phpredis#connect
https://github.com/phpredis/phpredis#pconnect-popen
> Added missing arguments for connect and pconnect

- redis/Redis.php
https://github.com/phpredis/phpredis#streams
https://youtrack.jetbrains.com/issue/WI-30713
> Added redis streams functions

- redis/Redis.php
https://github.com/ukko/phpredis-phpdoc/pull/38
> Added echo as normal method

- http/http3.php
See https://mdref.m6w6.name/http
> Update http3.php (pecl/http using version 3.2.0)

- solr/SolrClient.php
- was: SolrUpdateResponse, should be: SolrQueryResponse;
http://php.net/manual/en/solrclient.query.php
> Fixed an incorrect @return type of SolrClient::query

- iconv/iconv.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jetbrains/phpstorm-stubs/478)
> [+]: fix iconv phpdoc for return

- meta/.phpstorm.meta.php
- tests/Parsers/ExpectedFunctionArgumentsInfo.php
- tests/Parsers/MetaExpectedArgumentsCollector.php
- tests/Parsers/StubParser.php
- tests/TestData/Providers/PhpStormStubsSingleton.php
- tests/TestData/Providers/StubsTestDataProviders.php
- tests/TestStubs.php
- tests/TestStubsMetaExpectedArguments.php
Basic sanity checks, can improve in future though.
> Add test for checking correctness of expectedArguments meta

- standard/standard_8.php
Fixed issue: WI-45155 https://youtrack.jetbrains.com/issue/WI-45155
> Fix WI-45155: Fixed array_push and array_unshift stub as of PHP 7.3

- meta/.phpstorm.meta.php
See changes..
Reference:
http://php.net/manual/de/function.html-entity-decode.php
> Added html_entity_decode arguments to .phpstorm.meta.php

- redis/RedisCluster.php
Updated RedisCluster::scan() function signature and docs.
See [WI-44414](https://youtrack.jetbrains.com/issue/WI-44414)
> RedisCluster::scan()

- SaxonC/SaxonC.php
Stubs are based on the API docs at https://www.saxonica.com/saxon-c/doc/html/index.html#php-api,
with a couple of fixes for typos and obvious errors.
>  Add stubs for the Saxon/C extension

- Core/Core_c.php
This is #511 without `@internal` annotation. Just docs.
> Add traversable docs

- dom/dom_c.php
Adds possible false return on errors.
> Fix `query` return type

- PDO/PDO.php
This is a fix for the issue detailed in https://youtrack.jetbrains.com/issue/WI-45324
> Add `@throws` for PDOStatement::execute

- dom/dom_c.php
https://secure.php.net/manual/en/domnodelist.item.php
> DOMNodeList::item() returns DOMNode instead of DOMElement

- geoip/geoip.php
- meta/.phpstorm.meta.php
YouTrack issue: https://youtrack.jetbrains.com/issue/WI-45203
> Added new functions of geoip 1.1.0 WI-45203

- dom/dom_c.php
Reverts JetBrains/phpstorm-stubs#515
@MaXal @smoench here is test code: https://3v4l.org/VsnW7
> Revert "Revert "DOMNodeList::item() returns DOMNode instead of DOMElement""

- PDO/PDO.php
- dom/dom_c.php
- session/session.php
- standard/standard_9.php
Hello, 
This PR adds param types and default args to 
* `DOMDocument::__construct` 
* `sizeof`
* `assert`
* `PDOStatement::setFetchMode`
* `session_set_save_handler`
> Default args

- dom/dom.php
> Fixed PhpDoc for dom_import_simplexml() stub

- standard/standard_7.php
http://php.net/manual/en/function.unpack.php
> Fix missing default value for unpack()

- meta/.phpstorm.meta.php
> Add expected arguments for parse_url URL components

- meta/.phpstorm.meta.php
> Add expected arguments for IMAGETYPE and exif sections

- FFI/FFI.php
Adds autocomplete and a brief description of the FFI extension from the current php-src master (PHP 8.0.0-dev) branch.
Relation link: https://github.com/dstogov/php-ffi
> Add ffi extension support

- meta/.phpstorm.meta.php
> Add expected arguments for array_change_key_case

- date/date.php
- pgsql/pgsql.php
- standard/standard_0.php
and
* `pg_fetch_all`
* `date_diff`
* `date_time_set`
> Directory::read, Directory::close, Directory::rewind default args

- mongodb/mongodb.php
See http://php.net/manual/en/class.mongodb-driver-manager.php for up-to-date interface
See issue https://youtrack.jetbrains.com/issue/WI-45538
> update stub to reflect current MongoDB\Driver\Manager

- SPL/SPL_c1.php
Added the default constructor flags to the following SPL iterator classes:
* FilesystemIterator
* RecursiveDirectoryIterator
* GlobIterator
* MultipleIterator
> Added default flags to SPL iterator constructors

- standard/standard_8.php
See https://www.php.net/manual/en/function.ob-implicit-flush.php
> Fix PhpDoc and default for ob_implicit_flush

- standard/standard_defines.php
*see changes*
Taken from https://www.php.net/manual/en/function.flock.php
> Add PhpDoc for LOCK constants

- standard/standard_defines.php
*see changes*
Taken from https://www.php.net/manual/en/function.htmlspecialchars.php
> Add PhpDoc for ENT constants

- redis/Redis.php
https://github.com/phpredis/phpredis/issues/760
phpredis now support the options but the stubs not
> Add support for zAdd options like XX|NX and so on

- yaf/yaf.php
- yaf/yaf_namespace.php
- yar/yar.php
> Fix stub for Yaf 

- standard/standard_defines.php
> Fix PhpDocs for standard defines

- SPL/SPL_c1.php
https://www.php.net/manual/en/splfileobject.fputcsv.php
> Make SplFileObject::fputcsv() parameter name compatible with PHP documentation

- intl/intl.php
https://www.php.net/manual/en/class.intlgregoriancalendar.php
> Fixed parent of IntlGregorianCalendar

- SimpleXML/SimpleXML.php
Reverts JetBrains/phpstorm-stubs#570
> Revert "SimpleXML: better return annotation for xpath"

- mongodb/mongodb.php
https://php.net/manual/en/class.mongodb-bson-timestamp.php
> MongoDB: Timestamp needs to implement TimestampInterface

- Core/Core_c.php
See https://www.php.net/manual/en/closure.call.php
> Fixed Closure::call() parameter name

- standard/standard_8.php
https://github.com/JetBrains/phpstorm-stubs/blob/master/sockets/sockets.php#L1299
> Removed duplicate function

- stomp/stomp.php
https://www.php.net/manual/en/book.stomp.php
issue - https://youtrack.jetbrains.com/issue/WI-46583
> Add stubs for pecl-stomp php extension

- yaml/yaml.php
This file could use a reformat. I've stayed consistent with the existing style though.
> Fixed signature of yaml_emit()

- LevelDB/LevelDB.php
references:
https://github.com/reeze/php-leveldb/commit/19c1eb2ac32491367460211bfa61750a18854835
https://github.com/reeze/php-leveldb/commit/7997ba8d95387d8cc3d8bd5c30fce8e68ae7acc0
> fix stub of LevelDBWriteBatch::__construct()

- redis/Redis.php
Added a return type and a note about closing persistent connections, as mentioned in the docs https://github.com/phpredis/phpredis#close
> Add more info for Redis::close

- Core/Core.php
- standard/basic.php
https://3v4l.org/FnIA6
https://3v4l.org/pAMNL
https://3v4l.org/l6e0s
https://3v4l.org/Zr7bL
https://3v4l.org/c8XeZ
https://3v4l.org/4Woq7
> Fixed extensions of some functions

- rdkafka/RdKafka/Conf.php
- rdkafka/RdKafka/KafkaConsumer.php
- rdkafka/RdKafka/Message.php
- rdkafka/RdKafka/ProducerTopic.php
This PR resolves: https://youtrack.jetbrains.com/issue/WI-46652
> [WI-46652] Updated ext-rdkafka stubs to 3.1

- meminfo/meminfo.php
This PR resolves: https://youtrack.jetbrains.com/issue/WI-46655
> [WI-46655] Add ext-meminfo stub

- Core/Core_c.php
- standard/standard_9.php
> Move AssertionError to right extension

- standard/standard_4.php
> Add link in PhpDocs to list of PHP.INI directives

- crypto/crypto.php
adapted from https://github.com/bukka/php-crypto/blob/5f26ac91b0ba96742cc6284cd00f8db69c3788b2/docs/Crypto.php
> added pecl-crypto stub

- standard/standard_6.php
https://youtrack.jetbrains.com/issue/WI-47086
> [WI-47086] Fixed stream_set_blocking mode type parameter

- dom/dom_c.php
This is in line with other stubs.
> DOM: document nullable return types & properties

- amqp/amqp.php
`AMQPExchange::publish() expects parameter 2 to be string, null given`
> Change \AMQPExchange::publish route arg default value

- standard/standard_0.php
Fixes an issue where comment would not render properly in intellij using php plugin
> Update standard_0.php regarding strspn

- redis/Redis.php
the 2 optional arguments are missing
> Add maxlength and approximate argument to Redis::xadd

- Core/Core_c.php
- intl/intl.php
And ...
+ ErrorException default arg
> IntlDateFormatter::__construct param types and default args

- FFI/FFI.php
Change php version from 8.0 to 7.4
See: https://www.php.net/manual/ru/class.ffi.php
> Actualize FFI PHP version

- ldap/ldap.php
ldap_modify_batch() does return a boolean, depending on success
https://www.php.net/ldap-modify-batch
> Add missing ldap_modify_batch() return type

- redis/Redis.php
- redis/RedisCluster.php
add SERIALIZER_MSGPACK and SERIALIZER_JSON
> update PhpRedis serialization consts (sorry there was more)

- dba/dba.php
- dom/dom.php
- iconv/iconv.php
- intl/intl.php
- mysqli/mysqli.php
- openssl/openssl.php
- sockets/sockets.php
- sqlsrv/sqlsrv.php
-> found via https://github.com/voku/phpstorm-stubs/tree/return_type_fixes_v2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jetbrains/phpstorm-stubs/628)
> re-add some return-type fixes

- pcntl/pcntl.php
- pcntl_async_signals parameter is optional;
- pcntl_async_signals and pcntl_signal_get_handler description fixes;
> pcntl functions update

- redis/Redis.php
all of the set based commands accept any value if a serializer is set
see https://github.com/phpredis/phpredis#setoption
and https://github.com/ukko/phpredis-phpdoc/issues/31
> If a serilaizer is specified any value can be passed

- meta/.phpstorm.meta.php
I wonder should this be moved to `amqp/.phpstorm.meta.php` file?
> Add amqp meta

- redis/Redis.php
Update signatures to phpredis 5.0.1
Include changes from PR: 
https://github.com/ukko/phpredis-phpdoc/pull/53
https://github.com/ukko/phpredis-phpdoc/pull/54
> update phpredis to 5.0.1

- mbstring/mbstring.php
mb_encode_numericentity and mb_decode_numeric_entity can return false and null as shown here:
https://3v4l.org/runAT
> Update mb_* return types

- tests/TestData/mutedProblems.json
Mute parameter mismatch failures for strtr function
> Mute parameter mismatch failures for strtr function

- mysqli/mysqli.php
This method doesn't have any parameters.
https://github.com/php/php-src/blob/a43679632b97b513d6e2913d90e24d0915e1b486/ext/mysqli/mysqli_fe.c#L639
> Update mysqli_stmt::get_warnings() parameters

- standard/standard_3.php
These functions return `FALSE` value when receive unexpected argument.
```php
<?php
var_dump(ceil([])); // => false
var_dump(floor([])); // => false
var_dump(round([])); // => false
```
see PHP manual pages:
* https://www.php.net/round
* https://www.php.net/floor
* https://www.php.net/ceil
> round(), floor() and ceil() return float or false

- mbstring/mbstring.php
> Fix mb_ereg and mb_eregi reference parameters

- pcre/pcre.php
Ref: https://youtrack.jetbrains.com/issue/WI-45513
> Fixes incorrect signature of preg_split in pcre.php

- Reflection/Reflection.php
Fixes [WI-48755](https://youtrack.jetbrains.com/issue/WI-48755)
> Add deprecation for inheritor of `Reflector` interface

- SPL/SPL_c1.php
https://youtrack.jetbrains.com/issue/WI-41657
> Fix docblock alignment in SPL_c1

- SPL/SPL_c1.php
[php doc fix](https://github.com/php/doc-en/commit/cd889d2046cfd38d6f9ce7a6aecc498454793c65#diff-09a780c5d869f2ff12c548f33d0e8df7)
> Fix SplFileObject::fwrite docs

- date/date_c.php
- date/date_d.php
- tests/TestData/mutedProblems.json
> DATE_COOKIE/DateTime::COOKIE definitions are incorrect

- SPL/SPL.php
- SPL/SPL_c1.php
> Replace mixed return types in SPL.

- standard/standard_8.php
Fix for issue [WI-45819](https://youtrack.jetbrains.com/issue/WI-45819)
> Fixed stub for array_multisort

- intl/intl.php
Fix for issue [WI-40346](https://youtrack.jetbrains.com/issue/WI-40346)
> Fixed resourcebundle_locales stub

- standard/_types.php
- standard/standard_0.php
- standard/standard_1.php
- standard/standard_2.php
- standard/standard_3.php
- standard/standard_4.php
- standard/standard_6.php
- standard/standard_9.php
> Replace mixed return types in standard.

- standard/standard_4.php
According to https://www.php.net/manual/en/function.unserialize.php
> change return type of unserialize to mixed

- composer.json
Updated library for unit testing - locally it works great, I mean that CI say the same :)
> Updated PHPUnit to version 8

- gd/gd.php
- pcre/pcre.php
- standard/standard_1.php
- standard/standard_5.php
- standard/standard_6.php
- standard/standard_7.php
- standard/standard_8.php
Fixes https://youtrack.jetbrains.com/issue/WI-45612
> Fix malformed and missing code blocks

- Reflection/Reflection.php
Fixed argument to be optional
https://www.php.net/manual/en/reflectionproperty.getvalue.php
> ReflectionProperty::getValue optional argument

- redis/Redis.php
https://github.com/ukko/phpredis-phpdoc/releases/tag/5.0.1-beta6
> Update phpredis to 5.0.1-beta6

- date/date_c.php
Could not click on a documentation link
> Added https:// to @link

- meta/.phpstorm.meta.php
- standard/standard_1.php
Str_replace returns array if the subject is an array and returns string otherwise. So my intention is to set return type based on the third argument type. Does this work?
> Dynamic str_replace return type

- standard/password.php
- tests/Model/PHPConst.php
- tests/Model/PHPDefineConstant.php
Default value for PASSWORD_DEFAULT should be null. Related test is fixed to properly process null values
> fix default value for PASSWORD_DEFAULT and fix tests

- redis/Redis.php
Update Redis constants based on:
- https://github.com/phpredis/phpredis/blob/db446138c533dfd66df729b92d610f84514f3828/redis.c#L668-L738
- https://github.com/phpredis/phpredis/blob/db446138c533dfd66df729b92d610f84514f3828/common.h#L73
> Update Redis constants

- sqlsrv/sqlsrv.php
Missing default in sqlsrv_get_field
> sqlsrv_get_field optional parameter

- com_dotnet/com_dotnet.php
Based on:
https://www.php.net/manual/en/book.com.php
https://github.com/php/php-src/tree/master/ext/com_dotnet
> com_dotnet fix optional parameters

- ftp/ftp.php
This PR adds false type when documented in comment.
> add false types on ftp_* as documented

- mysqli/mysqli.php
https://www.php.net/manual/en/mysqli.store-result.php
> Adding optional parameter to mysqli::store_result

- event/event.php
Used NAN to keep the type non-nullable.
> Fix event optional arguments

- mongodb/mongodb.php
Problems discovered via phpstan analysis.
> Fix minor mistakes in mongodb

- PhpStormStubsMap.php
- blackfire/blackfire.php
This PR adds stubs for the `\BlackfireProbe` class, provided by the Blackfire extension.
> Add stubs for BlackfireProbe

- interbase/interbase.php
- meta/.phpstorm.meta.php
fixes issue [WI-51806](https://youtrack.jetbrains.com/issue/WI-51806)
> Added firebird fbird_* signatures, fixes #WI-51806

- sodium/sodium.php
Added missing link and since tags based on php docs. Added throws tag based on observed behavior
> Add missing link, throws, and since annotations to sodium_crypto_secretbox_open

- standard/standard_6.php
- https://heap.space/xref/php-src/ext/standard/streamsfuncs.c?r=bb6f3740#361
- https://heap.space/xref/php-src/ext/standard/streamsfuncs.c?r=bb6f3740#328
- https://heap.space/xref/php-src/ext/standard/streamsfuncs.c?r=bb6f3740#294
> Fix stream_* types

- standard/standard_2.php
References:
https://youtrack.jetbrains.com/issue/WI-52602
https://www.php.net/manual/en/function.urlencode.php
> WI-52602 Fix RFC reference for urlencode function.

- rdkafka/RdKafka/Producer.php
Ref: https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/class.rdkafka-producer.html
> Add missed RdKafka\Producer::flush and purge

- memcached/memcached.php
This resolves https://youtrack.jetbrains.com/issue/WI-52588.
> Add definition for Memcached::GET_EXTENDED flag.

- redis/Redis.php
https://github.com/phpredis/phpredis/pull/931
> Redis: add pipeline funciton

- PhpStormStubsMap.php
- redis/RedisSentinel.php
This PR adds doc stubs for the phpredis extension's RedisSentinel class.
I look forward to your feedback.
> Add auto-completion for phpredis' RedisSentinel Class

- mysqli/mysqli.php
Reference: https://www.php.net/manual/en/mysqli.connect-errno.php
> Fix $mysqli->connect_errno return type

- SPL/SPL_f.php
> Fixed parameter type hint for iterator_to_array, iterator_count and iterator_apply functions

- rdkafka/RdKafka/KafkaConsumer.php
For review purposes: https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-kafkaconsumer.offsetsfortimes.html and https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-kafkaconsumer.querywatermakoffsets.html
> Added queryWatermarkOffsets and offsetsForTimes for rdkafka

- Reflection/Reflection.php
Some are documented in PHP documentation - I expect all should be same
> Fixed Reflection*::export() @return annotations

- pcre/pcre.php
See https://github.com/vimeo/psalm/pull/3565
> preg_grep returns false when pattern cannot be compiled

- Core/Core.php
- standard/standard_1.php
> fix "Less than" sign in some phpdocs

- ds/ds.php
According to [PHPSTAN](https://github.com/phpstan/phpstan/issues/3470), some methods were missing in the Map class and others. I amended my contribution.
PS: I closed my original PR #832 in that matter because it continued the old branch on my side with a cluttered commit history. I opened a new branch to keep the contribution clean.
> Amended data structures

- decimal/decimal.php
According to the official repo: https://github.com/php-decimal/stubs
> Updated Decimal extension stubs

- SimpleXML/SimpleXML.php
Reuse methods signatures from SimpleXMLIterator since it's safe to assume that these methods will be used in iterator access for this class
> WI-53902 Make SimpleXMLElement implement Iterator

- redis/Redis.php
Remove duplicate comments from Redis.set()
> Remove duplicate comments

- PhpStormStubsMap.php
- xdebug/xdebug.php
see https://xdebug.org/docs/remote#xdebug_is_debugger_active
> added xdebug_is_debugger_active()

- meta/.phpstorm.meta.php
https://www.php.net/manual/en/function.mb-convert-case.php
Meta completion support for new modes added in PHP 7.3
> Update meta for mb_convert_case constants

- redis/Redis.php
As mentioned here: https://github.com/phpredis/phpredis/blob/master/arrays.markdown
> Update Redis.php stub with RedisArray::_instance

- standard/standard_4.php
As documented in https://www.php.net/error_get_last
Thanks
> error_get_last can return null

- bcmath/bcmath.php
For https://youtrack.jetbrains.com/issue/WI-54390
> Update information for bcscale()

- PhpStormStubsMap.php
- SaxonC/SaxonC.php
From https://www.saxonica.com/saxon-c/documentation/index.html#!api/saxon_c_php_api
> fix(saxon): update API links and add missing Xslt30Processor class

- openssl/openssl.php
openssl_decrypt see https://www.php.net/manual/en/function.openssl-decrypt.php
$options = 0
> php doc openssl_decrypt $options = 0

- standard/standard_1.php
For reference see:
- https://www.php.net/manual/en/function.chunk-split.php
- https://svn.php.net/viewvc/phpdoc/en/trunk/reference/strings/functions/chunk-split.xml?revision=297028&view=markup
or
- https://github.com/php/doc-en/blob/626c823ad3499e580fd64e8f45dd5da32702787c/reference/strings/functions/chunk-split.xml#L14-L15
> chunk_split: fix default values

- redis/Redis.php
- redis/RedisCluster.php
_Assuming this does not fall under 'unnecessary changes' as this is the actual 'phpdoc' you get to see in your IDE when 'using' the stub_
> Minor typo fix in Redis.php stub

- composer.json
Add [branch alias](https://getcomposer.org/doc/articles/aliases.md#branch-alias) `2020.x` to `master`
> Update composer.json: alias of master branch

- standard/_types.php
- tests/StubsTest.php
https://wiki.php.net/rfc/magic-methods-signature
> WI-54641 Add type declarations to magic method signatures

- ldap/ldap.php
https://github.com/php/php-src/commit/550a4f2fa89c3d3bc858aa81c62dbfa0f59f0e7c
> Deprecated LDAP functions removed

- rdkafka/RdKafka.php
- rdkafka/RdKafka/Conf.php
- rdkafka/RdKafka/KafkaConsumer.php
- rdkafka/RdKafka/Queue.php
I added some more fixes, i also created a PR for the  doc on our side, for wrong & missing stuff:
https://github.com/arnaud-lb/php-rdkafka-doc/pull/50
> [rdkafka] fix types, add missing funcs

- meta/.phpstorm.meta.php
- standard/standard_8.php
https://github.com/php/php-src/commit/46d22e435f43529aa55b54460dd265c4bd22409f
> ob_implicit_flush php 8 signature

- PhpStormStubsMap.php
- gd/gd.php
https://php.watch/versions/8.0/gdimage
> Add \GdImage class

- Reflection/Reflection.php
- Reflection/ReflectionClass.php
- Reflection/ReflectionClassConstant.php
- Reflection/ReflectionExtension.php
- Reflection/ReflectionFunction.php
- Reflection/ReflectionMethod.php
- Reflection/ReflectionObject.php
- Reflection/ReflectionParameter.php
- Reflection/ReflectionProperty.php
- Reflection/Reflector.php
- SPL/SPL_c1.php
- gd/gd.php
- mbstring/mbstring.php
- regex/ereg.php
- session/session.php
- standard/basic.php
- standard/standard_1.php
- standard/standard_3.php
- standard/standard_4.php
- standard/standard_5.php
- standard/standard_7.php
- standard/standard_8.php
Reverts JetBrains/phpstorm-stubs#936
> Revert "Deprecations"

- redis/Redis.php
PR for issue https://youtrack.jetbrains.com/issue/WI-56694
> (redis) Add COMPRESSION_LZ4 constant

- yaf/yaf.php
Update yaf.php add response method
> Update yaf.php add response method

- Reflection/ReflectionParameter.php
> Fix typo in deprecation message

- standard/standard_2.php
These functions have effects on the global random state.
Related issue: https://github.com/phpstan/phpstan/issues/4091
> rand() and mt_rand() are not pure

- .travis.yml
- Core/Core_c.php
- Dockerfile
- pcntl/pcntl.php
- standard/standard_6.php
- tests/StubsTest.php
* Update php to rc4 and fix related problems
* Add Travis job to check alive links in phpdoc
* Cleanup
> Update php to rc 4 and add separate travis job to run links check

- tests/Model/PHPFunction.php
- tests/Model/PHPMethod.php
- tests/Model/StubProblemType.php
- tests/StubsTest.php
- xdebug/xdebug.php
Remove types validation based on docs
all functions have typehints now and verified via reflection
> Remove types validation based on docs

- Phar/Phar.php
https://www.php.net/manual/en/phardata.extractto.php
> per php.net null is allowed for PharData->extractTo() $files arg

- mbstring/mbstring.php
- standard/standard_1.php
- standard/standard_9.php
- tests/Model/PHPClass.php
- tests/Model/PHPFunction.php
- tests/Model/PHPMethod.php
- tests/Model/PHPParameter.php
- tests/Model/StubProblemType.php
- tests/StubsTest.php
- tests/TestData/mutedProblems.json
+ fix some parameter testing problems
> Add test to check nullable parameters in php < 7.1

- ldap/ldap.php
Source: https://www.php.net/manual/en/migration73.new-functions.php
> Fix @since annotation for ldap_add_ext and ldap_mod_add_ext

- SPL/SPL_f.php
See example: https://github.com/phpstan/phpstan/issues/4126
> iterator_to_array is not pure

- tests/StubsTest.php
to pass cases like array|int & int|array
> compare typehints as arrays of types instead of strings

- SaxonC/SaxonC.php
See:
https://saxonica.plan.io/issues/4789
https://saxonica.plan.io/issues/4679
> Update SaxonC docs

- sqlite3/sqlite3.php
See: https://www.php.net/manual/en/sqlite3.enableexceptions.php
> SQLite3::enableExceptions() return value

- FFI/FFI.php
* see https://github.com/php/php-src/blob/master/ext/ffi/ffi.stub.php#L64
* https://www.php.net/manual/en/ffi.isnull.php
> Add FFI::isNull(CData $ptr): bool

- standard/standard_1.php
This reverts commit cae81c24
overloading of function isn't supported
> Revert "add more specific types for "implode()""

- standard/standard_1.php
> move comment before attribute

- aerospike/aerospike.php
- date/date_c.php
- gd/gd.php
- gmp/gmp.php
- grpc/grpc.php
- igbinary/igbinary.php
- imap/imap.php
- intl/intl.php
- ldap/ldap.php
- mapscript/mapscript.php
- mbstring/mbstring.php
- parallel/parallel/Channel.php
- radius/radius.php
- sockets/sockets.php
- sodium/sodium.php
- sqlsrv/sqlsrv.php
- standard/standard_7.php
- standard/standard_8.php
- v8js/v8js.php
- xcache/xcache.php
- xlswriter/xlswriter.php
- xmlwriter/xmlwriter.php
- yaf/yaf.php
- yar/yar.php
- zend/zend.php
- zookeeper/zookeeper.php
found via https://github.com/voku/php-doc-fixer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jetbrains/phpstorm-stubs/991)
> More type fixes

- date/date.php
- date/date_c.php
Sources:
- https://www.php.net/manual/en/datetimezone.getlocation.php
- https://www.php.net/manual/en/datetimezone.getoffset.php
- https://www.php.net/manual/en/datetimezone.gettransitions.php
- https://www.php.net/manual/en/datetimezone.listabbreviations.php
- https://www.php.net/manual/en/datetimezone.listidentifiers.php
> Fix DateTimeZone signatures

- PDO/PDO.php
- imap/imap.php
- mbstring/mbstring.php
- odbc/odbc.php
- pgsql/pgsql.php
- standard/standard_7.php
- standard/standard_9.php
-> https://youtrack.jetbrains.com/issue/WI-55651
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jetbrains/phpstorm-stubs/1005)
> move attributes between phpdoc and signature

- bcmath/bcmath.php
- tests/StubsTypeHintsTest.php
to pass several duplicated functions declared with #[PhpStormStubsElementAvailable]
> check return typehint in duplicated functions for latest php version

- Dockerfile
- PhpStormStubsMap.php
- gd/gd.php
Add gd extension to docker image and update stubs according to reflection
> Update gd stubs

- imagick/imagick.php
(based on https://github.com/Imagick/imagick sources)
> Mark deprecated imagick methods

- gd/gd.php
- ldap/ldap.php
- mbstring/mbstring.php
- mysqli/mysqli.php
- openssl/openssl.php
- qodana.yaml
- sockets/sockets.php
- standard/standard_1.php
- standard/standard_7.php
- tests/Model/PHPDocElement.php
- tests/Model/PHPFunction.php
- tests/Model/PHPParameter.php
- tests/StubsTest.php
- tests/TestData/Providers/EntitiesFilter.php
- tests/TestData/Providers/Reflection/ReflectionParametersProvider.php
- tests/TestData/Providers/Stubs/StubsParametersProvider.php
- tests/TestData/mutedProblems.json
Optional parameters in stubs should be defined by default value or by `[optional]` note in related phpdoc. Vararg parameters are parsed as optional as well
> add test for optional parameters

- Inspections.xml
- qodana.yaml
- tests/Parsers/MetaExpectedArgumentsCollector.php
- tests/StubsMetaExpectedArgumentsTest.php
- tests/StubsPhpDocTest.php
- tests/StubsTest.php
- tests/StubsTypeHintsTest.php
- tests/TestData/Providers/EntitiesFilter.php
- tests/TestData/Providers/Stubs/StubMethodsProvider.php
Enabled almost all phpstorm inspections to try most strict approach with custom inspections profile
> qodana: try custom inspections profile

- PDO/PDO.php
Adds recent attribute constants for pdo_oci.
> PDO: Add pdo_oci attribute constants.

- standard/standard_8.php
add some clarifications about `array_merge` behavour, reword arrays parameter description, add notice about 7.4 changed requirements
> clarify the array_merge behaviour

- redis/Redis.php
fixes https://github.com/phpstan/phpstan/issues/4531
> Redis auth method also accepts array

- sodium/sodium.php
Hello,
I fix var name in body function with parameter name
but i think it's useless cause lot of function here doesn't have body.
Do you want to delete all body for this file ?
> Fix var name in sodium.php

- redis/Redis.php
- redis/RedisCluster.php
Hi there
phpredis introduced those two new constants a while ago with version 5.3.0
https://github.com/phpredis/phpredis/issues/548
> Add new redis scan prefix constants

- event/event.php
update event input params type and return type
> update event input params type and return type

- event/event.php
update event input params type, return type, methods and constants.
> update event input params type, return type, methods and constants.

- Reflection/ReflectionFunctionAbstract.php
See https://github.com/php/php-src/blob/269c8dac1d56ee85d71ae94d9b28dd7d8e8de7b7/ext/reflection/php_reflection.c#L1763
> Fix ReflectionFunctionAbstract::getStartLine() return type

- Reflection/ReflectionFunctionAbstract.php
- Reflection/ReflectionParameter.php
- Reflection/ReflectionProperty.php
Generally, recreated #1039 with rebased version of code
> fix return types for some reflection functions

- couchbase_v3/couchbase.php
Note that braces were moved to new line after I run cs-fix on the file
> update stubs for couchbase 3.1.2

- standard/standard_9.php
https://www.php.net/manual/en/function.array-map.php
> array_map callback can be null

- blackfire/blackfire.php
These can be used when using Blackfire Monitoring.
> Add setTransactionName() and ignoreTransaction() methods to BlackfireProbe stub

- sqlite3/sqlite3.php
Fixes https://youtrack.jetbrains.com/issue/WI-60012
> add boolean values to sqlite3 returns

- FFI/.phpstorm.meta.php
Added completition for `FFI::addr()` function.
> Add FFI::addr() autocomplete

- Parle/Parser.php
- Parle/RParser.php
https://github.com/weltling/parle/commit/a34fbdcc264422c1a5f9e315866b12daba2f5da0
> fix parle stub ERROR_UNKNOWN_TOKEN

- intl/intl.php
Update message formatter constuctor in accordance with https://www.php.net/manual/en/messageformatter.create.php
> Update MessageFormatter constructor doc

- Reflection/ReflectionFunctionAbstract.php
- Reflection/ReflectionParameter.php
- Reflection/ReflectionProperty.php
Use language level type aware attribute for php >= 8.1
> WI-61052 Add ReflectionIntersectionType to getType methods

- sqlite3/sqlite3.php
SQLite3::backup() returns boolean, see: https://www.php.net/manual/en/sqlite3.backup.php
> Update sqlite3.php - SQLite3::backup() returns boolean

- session/SessionHandler.php
- session/session.php
Fixes based on https://github.com/JetBrains/phpstorm-stubs/pull/1152
> Typehinting for sessions fixes

- filter/filter.php
see changelog section of https://www.php.net/manual/en/filter.filters.validate.php
> add missing @since 8.0 to `FILTER_VALIDATE_BOOL`

- tests/StubsPhpDocTest.php
- Added Generics PHPDoc parsing for tests;
- `@template-implements` added as a valid PHPDoc tag for tests;
> StubsPhpDocTest improvements

- session/SessionHandler.php
See https://www.php.net/manual/en/sessionhandlerinterface.gc.php and https://www.php.net/manual/en/sessionhandlerinterface.read.php
> Fix return types for SessionHandlerInterface

- ftp/ftp.php
- ftp_rawlist: https://www.php.net/manual/de/function.ftp-rawlist.php
- ftp_nlist: https://www.php.net/manual/de/function.ftp-nlist.php
> optimize some ftp phpdocs

- Core/Core_c.php
- dom/dom_c.php
- ftp/Connection.php
- gd/GdFont.php
- hash/hash.php
- imap/Connection.php
- ldap/Connection.php
- ldap/Result.php
- ldap/ResultEntry.php
- mysqli/mysqli.php
- tests/BaseClassesTest.php
- tests/Model/PHPClass.php
- tests/TestData/Providers/Reflection/ReflectionClassesTestDataProviders.php
- tests/TestData/mutedProblems.json
- xml/xml.php
- zlib/zlib.php
Add tests to check final attribute on classes and update classes
> Final classes test

- PDO/PDO.php
fixed incorrect constant values and re-ordered the constant ascending by their value
see https://3v4l.org/O0hDh
refs https://github.com/phpstan/phpstan/issues/5985
> Fix `PDO::PARAM_*` constant values

- .github/workflows/main.yml
until it fully supports readonly properties and other PHP 8.1 features
> Temp disable csfixer

- mysqli/mysqli.php
Improve mysqli_fetch_* stubs.
Adjusted the stubs to the changes I made in the PHP manual over the past year.
I double-checked my changes, but please check again to make sure I didn't make any mistakes.
> Improve mysqli stubs

- Core/Core_c.php
- tests/TestData/mutedProblems.json
> `Exception::__clone()` and `Error::__clone()` are not final in PHP 8.1

- standard/standard_0.php
- tests/TestData/mutedProblems.json
See https://3v4l.org/688Ut or https://www.php.net/manual/en/directory.close.php
> `Directory` methods do not accept `$dir_handle` parameter since PHP 8.0

- Core/Core_c.php
- tests/TestData/mutedProblems.json
> `Closure::__invoke()` does not have any parameters in PHP

- redis/RedisCluster.php
See https://github.com/phpredis/phpredis/issues/2038 and https://github.com/vimeo/psalm/pull/7030
> Fix RedisCluster::setOption|getOption types

- standard/standard_1.php
add expected values for category in setlocale function
> [phpstorm-stubs] WI-64815 

- ds/ds.php
_Needs to be added to the docs, looking into it rn_
(https://github.com/php-ds/polyfill/blob/a0a08f391847de2db0959b483e882aa91c4a2b70/src/Set.php#L273)
> Add `Set::map()` into DS stubs

- redis/Redis.php
As specified in [official docs](https://github.com/phpredis/phpredis#return-value-142) , if MULTI is used:
> ... Once in multi-mode, all subsequent method calls return the same object until exec() is called.
> Fixed return type for methods when MULTI/EXEC is used.

- pgsql/pgsql.php
- tests/DockerImages/7.3/Dockerfile
- tests/DockerImages/7.4/Dockerfile
- tests/DockerImages/8.0/Dockerfile
Update pgsql stubs to suit all php versions
> Pgsql all php

- redis/Redis.php
https://github.com/phpredis/phpredis/blob/5.3.6/redis.c#L3403
https://redis.io/commands/role
> Add missing Redis::role() method

- SimpleXML/SimpleXML.php
- intl/intl.php
- openssl/openssl.php
The failed CIs for 8.x are not my fault ;)
> Replace some comments with the versions where the functions where added

- pdflib/PDFlib.php
Added descriptions to arguments and the return value, and added a link to the PDFlib manual, since the php.net link was broken (404).
> Update doc comment on pdflib::fit_table based on pdflib documentation

- dom/dom_c.php
- pcre/pcre.php
Fixes [WI-65511](https://youtrack.jetbrains.com/issue/WI-65511)
> Language injection for common function args

- Core/Core_c.php
This reverts commit fa229846721f4844c5ddcc4176f0b19b8d2a5e45. Filled WI-65964
> Revert "[phpstorm-stubs] remove redundant compatibility fix"

- Core/Core_c.php
- Reflection/ReflectionEnumBackedCase.php
- Reflection/ReflectionEnumUnitCase.php
inspired by [psalm php8.1 stub](https://github.com/vimeo/psalm/blob/4.x/stubs/Php81.phpstub)
> mark enum methods as pure

- meta/attributes/ArrayShape.php
Dimension is not a suitable word here. From purely mathematical point of view it would mean array of arrays of arrays.
> Improved wording

- Reflection/ReflectionClass.php
Follow-up of https://github.com/JetBrains/phpstorm-stubs/pull/1373
@isfedorov @williamdes @DmitryTronin please review.
> Leverage templating even more for ReflectionClass

- ds/ds.php
Discovered in https://github.com/phpstan/phpstan/issues/7232.
https://www.php.net/manual/en/ds-priorityqueue.peek.php
> Add missing `Ds\PriorityQueue#peek` method.

- memcached/memcached.php
Based on https://github.com/JetBrains/phpstorm-stubs/pull/1386/
> Added since tag for GET_EXTENDED

- dom/dom_c.php
A minor fix based on https://github.com/JetBrains/phpstorm-stubs/pull/1312
> Fixed getIterator return PHPDoc

- .github/workflows/main.yml
- phpunit.xml.dist
- tests/DockerImages/8.2/Dockerfile
As stated in a title. Using php:8.2.0alpha3-zts-alpine for now
> adding 8.2alpha support

- Reflection/ReflectionClass.php
https://youtrack.jetbrains.com/issue/WI-67785
> removed ReflectionClass::isReadOnly duplicate & added since tag

- standard/basic.php
for utf8_encode and utf8_decode
> fixed replacement pattern for deprecated functions

- Reflection/ReflectionProperty.php
- tests/BaseClassesTest.php
- tests/Model/PHPClass.php
- tests/Model/PHPProperty.php
- tests/Model/StubProblemType.php
- tests/Model/StubsContainer.php
- tests/TestData/Providers/Reflection/ReflectionClassesTestDataProviders.php
- tests/TestData/Providers/Reflection/ReflectionPropertiesProvider.php
They are: 
- testClassesReadonly  provider, 
- isReadonly PHPClass property, 
- removed nonexistent isReadonly ReflectionProperty property, 
- added CLASS_READONLY StubProblemType
> Added testClassesReadonly test & related adjustments

- gd/gd.php
- mbstring/mbstring.php
- standard/standard_4.php
Update function return types to more narrow versions based on php-src info
> https://youtrack.jetbrains.com/issue/WI-68167 

- standard/standard_4.php
- tests/StubsTypeHintsTest.php
- tests/TestData/Providers/Reflection/ReflectionFunctionsProvider.php
- tests/TestData/mutedProblems.json
Also musing "wrong return typehint" for that
> string|true fixes for print_r based on team discussion

- standard/standard_7.php
- tests/TestData/mutedProblems.json
return type based on reflection
> https://youtrack.jetbrains.com/issue/WI-68297 adjusting rewinddir 

- standard/standard_6.php
- standard/standard_9.php
- tests/TestData/mutedProblems.json
narrower types for 3 stream_get_ functions
note: muted related problems
> https://youtrack.jetbrains.com/issue/WI-68898

- standard/standard_1.php
https://youtrack.jetbrains.com/issue/WI-68897
added array shape for pathinfo @return
added ExpectedValues for $flags
> Adding array shape for 'pathinfo()' 

- tests/StubsPhpDocTest.php
a fix to allow https://github.com/JetBrains/phpstorm-stubs/pull/1437
> added template-covariant to the list of valid tags since we support it

- intl/intl.php
- tests/StubsTypeHintsTest.php
- tests/TestData/Providers/Reflection/ReflectionParametersProvider.php
- tests/TestData/mutedProblems.json
parameter in IntlBreakIterator::getPartsIterator should have type int
> [phpstorm-stubs] WI-69083 IntlBreakIterator::getPartsIterator fix

- standard/standard_1.php
Wording didn't make sense, updated wording to match official php docs
> Fixed wording for nl2br

- standard/standard_0.php
Updated some param and return descriptions for some functions, to better match PHP docs :)
> Updated wording to match php docs

- PDO/PDO.php
Cf https://www.php.net/manual/en/pdo.query.php
> Fix PDO::query param name

- composer.json
- redis/Redis.php
As I mentioned in my previous PR, here is the synced full stub file. I tried to reduce the changes to make diff smaller, but there are still a lot of changes.
> Sync redis stub with official file.

- zip/zip.php
> Added array shape for ZipArchive::statIndex and ::statName methods

- relay/Event.php
- relay/Relay.php
Sync with `https://builds.r2.relay.so/v0.6.2/relay.stub.php`
> Relay v0.6.2 stubs

- ds/ds.php
https://www.php.net/manual/en/class.ds-sequence.php  
https://www.php.net/manual/en/class.ds-vector.php  
etc.
implement ArrayAccess
> feat(ds): add missing ArrayAccess

- redis/Redis.php
> Fix typo in Redis.php

- random/random.php
Cf https://www.php.net/manual/en/function.random-int.php#refsect1-function.random-int-changelog
and https://www.php.net/manual/en/function.random-bytes.php#refsect1-function.random-bytes-changelog
> Update random_int and random_bytes exception thrown

- meta/.phpstorm.meta.php
See https://www.php.net/manual/en/class.spoofchecker.php
> Added meta for Spoofchecker setChecks and setRestrictionLevel method arguments

- relay/Relay.php
https://github.com/cachewerk/relay/releases/tag/v0.6.4
Tests are failing unrelated reason. I cannot retry them.
> Sync Relay v0.6.4 stubs

- redis/RedisCluster.php
As per https://github.com/phpredis/phpredis/blob/develop/redis_cluster.stub.php
> Update RedisCluster constructor

- imagick/imagick.php
According to https://github.com/php/doc-en/pull/2444
> Fix Imagick::scaleImage parameter name

- curl/curl.php
ref.: https://github.com/php/doc-en/pull/2591
> curl_multi_init: fix return description

- PhpStormStubsMap.php
- opentelemetry/opentelemetry.php
- tests/TestData/Providers/Stubs/PhpCoreStubsProvider.php
adding stubs for the opentelemetry extension: https://github.com/open-telemetry/opentelemetry-php-instrumentation
https://pecl.php.net/package/opentelemetry
> adding opentelemetry extension stubs

- PhpStormStubsMap.php
- relay/Relay.php
- relay/Sentinel.php
- relay/Table.php
Update [Relay](https://github.com/cachewerk/relay) stubs to match v0.6.8.
> Update Relay stubs to v0.6.8

- redis/Redis.php
Ref:
https://github.com/phpredis/phpredis/pull/1983/files
> Update phpredis docs of timeout option

- PhpStormStubsMap.php
- relay/Cluster.php
- relay/Relay.php
- relay/Table.php
Sync with Relay [v0.7.0 release](https://github.com/cachewerk/relay/releases/tag/v0.7.0).
The tests pass locally, I'm not sure why the tests are failing on `master` as well.
> Sync Relay stubs with v0.7.0

- Parle/Stack.php
Example:
```php
/** @var \Parle\Stack<int> $stack */
$stack = new \Parle\Stack();
$stack->push(42);
$n = $stack->top;
```
> Add template annotations for Parle\Stack

- SPL/SPL.php
Just small fix of very annoing thing for me (and not only, i believe)
> Fix ArrayObject offsetGet php-doc

- uv/uv_functions.php
Also update extension repository URL
Refs: https://github.com/amphp/ext-uv/blob/670a609efc36c9043be37bae4126f06ed30fde21/php_uv.c#L3607C64-L3607C96
> [UV] Add missing second argument to uv_run

- standard/standard_4.php
https://www.php.net/manual/en/function.header-remove
> Sync header_remove

- standard/standard_4.php
https://www.php.net/manual/en/function.headers-sent.php
> Sync headers_sent

- redis/Redis.php
Correct Redis types for php 8.2
> Correct Redis types for php 8.2

- session/SessionHandler.php
class doesn't implemetn SessionUpdateTimestampHandlerInterface anymore
> WI-77313 remove redundant methods.

- zip/zip.php
The function has been missing so far.
> Add missing `ZipArchive::getStreamIndex` function definition

- dom/dom_c.php
- dom/dom_n.php
- mysql/mysql.php
- mysqli/mysqli.php
- tests/Model/CommonUtils.php
- tests/Model/PHPDocElement.php
- tests/Model/PHPFunction.php
- tests/StubsTypeHintsTest.php
Should be reviewed, and merged as individual commits.
@nielsdos could you have a quick look to see if I didn't make a wrong assumption somewhere?
> Enhance `ext/dom` stubs

- imagick/imagick.php
See https://phpimagick.com/Imagick/getConfigureOptions
> Fix Imagick::getConfigureOptions()

- standard/standard_8.php
Refs:
- https://github.com/php/doc-en/blob/c532eceb157530671958a3ef2710bbda3f5ddf68/reference/array/functions/ksort.xml
- https://www.php.net/manual/en/function.ksort.php
> :book: Actualize "ksort" description according to the docs

- standard/standard_3.php
https://youtrack.jetbrains.com/issue/WI-81329
> [phpstorm-stubs] Fix typo in getrusage() parameter description WI-81329

- standard/standard_1.php
Updated explode function stub description to be more relevant with parameter name and php doc standard
> update explode function stubs 

- Core/Core_c.php
cc @isfedorov 
cf https://www.php.net/manual/en/class.errorexception.php
> Fix type in phpdoc of ErrorException

- solr/Documents/SolrDocument.php
- solr/Documents/SolrInputDocument.php
- solr/Queries/SolrCollapseFunction.php
- solr/Queries/SolrDisMaxQuery.php
- solr/Queries/SolrQuery.php
- solr/SolrClient.php
Mainly improving `optional` param signature by adding a default value.
cf https://www.php.net/manual/en/class.solrdismaxquery.php for instance
And a missing `@return void`
> Improve solr signatures
